/**
 * Loot drop tables. Hand-rolled named items, not procedural affix slop.
 * Each item carries a Taint cost — power has a price.
 *
 * Stat bonuses are LARGE — they live in the same numeric universe as the
 * rest of the game (HP in hundreds, ATK in tens). A relic weapon should
 * feel like a real spike, not a +1 trinket.
 */

import type { LootItem, LootRarity } from './types'

export const LOOT_POOL: LootItem[] = [
  // ---- Common ----
  {
    id: 'rusty-pick',
    name: 'PICARETA ENFERRUJADA',
    rarity: 'common',
    slot: 'weapon',
    atkBonus: 5,
    taint: 0,
    flavor: 'Era de algum minerador. Agora é seu problema.',
  },
  {
    id: 'pot-helm',
    name: 'CAPACETE DE PANELA',
    rarity: 'common',
    slot: 'helm',
    hpBonus: 20,
    taint: 0,
    flavor: 'Cheira a sopa antiga. Funciona.',
  },
  {
    id: 'string-charm',
    name: 'AMULETO DE BARBANTE',
    rarity: 'common',
    slot: 'trinket',
    spdBonus: 1,
    taint: 0,
    flavor: 'A criança que fez isso vai ter um futuro brilhante. Talvez.',
  },

  // ---- Uncommon ----
  {
    id: 'butcher-cleaver',
    name: 'CUTELO DO AÇOUGUEIRO',
    rarity: 'uncommon',
    slot: 'weapon',
    atkBonus: 15,
    taint: 0.2,
    flavor: 'O açougueiro reclamou. Por menos de cinco segundos.',
  },
  {
    id: 'iron-circlet',
    name: 'CIRCLET DE FERRO',
    rarity: 'uncommon',
    slot: 'helm',
    hpBonus: 40,
    taint: 0.2,
    flavor: 'Aperta um pouco. Mantém a cabeça no lugar — literalmente.',
  },
  {
    id: 'crow-foot',
    name: 'PÉ-DE-CORVO ENCANTADO',
    rarity: 'uncommon',
    slot: 'trinket',
    moveBonus: 1,
    spdBonus: 1,
    taint: 0.3,
    flavor: 'Sussurra direções erradas, mas você anda mais rápido.',
  },

  // ---- Cursed ----
  {
    id: 'screaming-axe',
    name: 'MACHADO QUE GRITA',
    rarity: 'cursed',
    slot: 'weapon',
    atkBonus: 30,
    taint: 0.8,
    flavor: 'Não para de gritar. O que ele grita... é seu nome verdadeiro.',
  },
  {
    id: 'bone-crown',
    name: 'COROA DE OSSO MENOR',
    rarity: 'cursed',
    slot: 'helm',
    hpBonus: 60,
    atkBonus: 5,
    taint: 0.9,
    flavor: 'O ex-dono também era ambicioso. Veja onde acabou.',
  },
  {
    id: 'ember-eye',
    name: 'OLHO DE BRASA',
    rarity: 'cursed',
    slot: 'trinket',
    rangeBonus: 1,
    atkBonus: 10,
    taint: 1.0,
    flavor: 'Vê três segundos no futuro. Geralmente, três segundos ruins.',
  },

  // ---- Relic ----
  {
    id: 'sundering-blade',
    name: 'LÂMINA DO ROMPIMENTO',
    rarity: 'relic',
    slot: 'weapon',
    atkBonus: 50,
    taint: 1.4,
    flavor: 'Cortou uma profecia em duas. A profecia ainda não percebeu.',
  },
  {
    id: 'pact-mantle',
    name: 'MANTO DO PACTO',
    rarity: 'relic',
    slot: 'helm',
    hpBonus: 90,
    spdBonus: 1,
    taint: 1.6,
    flavor: 'Os outros seis Underlords usaram. Você é o primeiro a sair vivo dele.',
  },
  {
    id: 'sigil-of-cinders',
    name: 'SIGILO DAS CINZAS',
    rarity: 'relic',
    slot: 'trinket',
    atkBonus: 20,
    rangeBonus: 1,
    moveBonus: 1,
    taint: 2.0,
    flavor: 'Toda vez que você bate, sente um pouco do reino também.',
  },

  /* ============================================================
   * LEGENDÁRIOS (v6) — 25 items, only drop from stage ≥ 14 or
   * Black Market. Stat budgets are deliberately above relic so a
   * single legendary can carry a whole minion. Taint is steep.
   * ============================================================ */

  // ---- WEAPONS (9) ----
  {
    id: 'leg-sword-bryan',
    name: 'BRYANNICA, A LÂMINA QUE GRITA NOMES',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 80,
    taint: 2.4,
    flavor: 'A espada de Bryan. Continua gritando "BRYAN!". Você se acostuma.',
  },
  {
    id: 'leg-axe-tyrant',
    name: 'MACHADO DO TIRANO PROVISÓRIO',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 70,
    hpBonus: 40,
    taint: 2.6,
    flavor: 'Pertenceu a um rei interino que reinou por 14 minutos. Ainda dá conta.',
  },
  {
    id: 'leg-spear-dawn',
    name: 'LANÇA DA AURORA TARDIA',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 60,
    rangeBonus: 1,
    taint: 2.5,
    flavor: 'O sol nasce três horas atrasado quando você empunha. Os heróis ficam tontos.',
  },
  {
    id: 'leg-hammer-vael',
    name: 'MARTELO DE VAEL DEPOSTO',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 90,
    spdBonus: -1,
    taint: 2.8,
    flavor: 'Pesa como uma cidade caída. Bate como uma cidade caindo.',
  },
  {
    id: 'leg-dagger-seven',
    name: 'PUNHAL DAS SETE COROAS',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 55,
    spdBonus: 2,
    moveBonus: 1,
    taint: 2.6,
    flavor: 'Uma lâmina pra cada coroa que tombou. Sete cortes pelo preço de um.',
  },
  {
    id: 'leg-bow-tyrella',
    name: 'ARCO DA TYRELLA APAGADA',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 50,
    rangeBonus: 2,
    taint: 2.5,
    flavor: 'Tyrella era a melhor arqueira do reino. "Era" porque você está com o arco.',
  },
  {
    id: 'leg-mace-cardinal',
    name: 'MAÇA DO CARDEAL ENTERRADO',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 75,
    hpBonus: 30,
    taint: 2.7,
    flavor: 'Cada batida soa como um sino de funeral. O cardeal te benze enquanto você massacra.',
  },
  {
    id: 'leg-glaive-twin',
    name: 'GLAIVE DA LUA GÊMEA',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 65,
    rangeBonus: 1,
    spdBonus: 1,
    taint: 2.7,
    flavor: 'Duas luas. Uma lâmina. Quem entender ganha; quem perguntar morre.',
  },
  {
    id: 'leg-scythe-reaper',
    name: 'CEIFEIRA DO ANO 814',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 100,
    hpBonus: -20,
    taint: 3.0,
    flavor: 'Colhe heróis como trigo. Te corta um pouquinho cada vez que você respira.',
  },

  // ---- HELMS (8) ----
  {
    id: 'leg-helm-submerged',
    name: 'COROA SUBMERSA, A AUTÊNTICA',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 150,
    atkBonus: 20,
    taint: 3.0,
    flavor: 'A original. As outras seis sabem disso. Por isso choram.',
  },
  {
    id: 'leg-helm-archon',
    name: 'ELMO DO ARCONTE ESQUECIDO',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 130,
    spdBonus: 1,
    taint: 2.8,
    flavor: 'Ninguém lembra do nome dele. Mas o elmo lembra de cada ferida que aparou.',
  },
  {
    id: 'leg-helm-iron-mother',
    name: 'CAPUZ DA MÃE-FERRO',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 180,
    moveBonus: -1,
    taint: 2.9,
    flavor: 'Pesa duas vidas. Te dá três.',
  },
  {
    id: 'leg-helm-eyes-of-vael',
    name: 'OLHOS DE VAEL\'THRAND',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 100,
    rangeBonus: 1,
    atkBonus: 15,
    taint: 2.8,
    flavor: 'Vê o reino do jeito que era. E do jeito que vai ficar quando você terminar.',
  },
  {
    id: 'leg-helm-cardinal-mitra',
    name: 'MITRA DO CARDEAL VIVO',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 120,
    atkBonus: 25,
    taint: 3.0,
    flavor: 'O cardeal não morreu. Ele só não está mais usando.',
  },
  {
    id: 'leg-helm-bone-mask',
    name: 'MÁSCARA DE OSSO DE DRAGÃO',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 140,
    atkBonus: 10,
    taint: 2.7,
    flavor: 'O dragão também não morreu. Mas isso é problema pra outro dia.',
  },
  {
    id: 'leg-helm-pact-circlet',
    name: 'TIARA DO PACTO DE FERRO',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 110,
    spdBonus: 2,
    taint: 2.9,
    flavor: 'Sete Underlords assinaram. Cinco se arrependeram. Você nem leu.',
  },
  {
    id: 'leg-helm-crown-of-fire',
    name: 'COROA DE FOGO PERMANENTE',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 90,
    atkBonus: 35,
    taint: 3.1,
    flavor: 'Queima desde 814. Não derrete o ferro. Derrete tudo o resto.',
  },

  // ---- TRINKETS (8) ----
  {
    id: 'leg-trinket-thrand-eye',
    name: 'OLHO DE VAEL DESTERRADO',
    rarity: 'legendary',
    slot: 'trinket',
    atkBonus: 30,
    rangeBonus: 2,
    moveBonus: 1,
    taint: 3.0,
    flavor: 'Vê o ataque inimigo antes do inimigo ver. Pisca em código.',
  },
  {
    id: 'leg-trinket-saint-finger',
    name: 'DEDO DO SANTO FALSIFICADO',
    rarity: 'legendary',
    slot: 'trinket',
    hpBonus: 80,
    atkBonus: 25,
    taint: 2.9,
    flavor: 'Não é dedo de santo. Mas o santo não vai reclamar — ele também é falso.',
  },
  {
    id: 'leg-trinket-sevenfold',
    name: 'AMULETO SETE-VEZES-FORJADO',
    rarity: 'legendary',
    slot: 'trinket',
    atkBonus: 25,
    spdBonus: 2,
    moveBonus: 1,
    taint: 2.8,
    flavor: 'Cada forja matou um ferreiro. O sétimo não morreu — virou amuleto.',
  },
  {
    id: 'leg-trinket-cinder-heart',
    name: 'CORAÇÃO DAS CINZAS',
    rarity: 'legendary',
    slot: 'trinket',
    hpBonus: 100,
    atkBonus: 20,
    taint: 3.0,
    flavor: 'Bate uma vez por século. Cada batida é uma cidade que cai.',
  },
  {
    id: 'leg-trinket-rune-of-six',
    name: 'RUNA DOS SEIS QUE FALHARAM',
    rarity: 'legendary',
    slot: 'trinket',
    hpBonus: 70,
    atkBonus: 30,
    rangeBonus: 1,
    taint: 3.1,
    flavor: 'Seis Underlords antes. Seis sumiram. A runa lembra de cada um.',
  },
  {
    id: 'leg-trinket-blackgate-key',
    name: 'CHAVE DO PORTÃO NEGRO',
    rarity: 'legendary',
    slot: 'trinket',
    spdBonus: 3,
    moveBonus: 2,
    atkBonus: 15,
    taint: 2.7,
    flavor: 'Abre qualquer porta. Inclusive as que ninguém deveria abrir. Inclusive a sua.',
  },
  {
    id: 'leg-trinket-tongue-of-iron',
    name: 'LÍNGUA DE FERRO DO PROFETA',
    rarity: 'legendary',
    slot: 'trinket',
    atkBonus: 40,
    rangeBonus: 1,
    taint: 2.9,
    flavor: 'O profeta não fala mais — você fala por ele. E ele tinha umas palavras escolhidas.',
  },
  {
    id: 'leg-trinket-final-coin',
    name: 'A ÚLTIMA MOEDA DO REINO',
    rarity: 'legendary',
    slot: 'trinket',
    hpBonus: 60,
    atkBonus: 25,
    spdBonus: 1,
    taint: 3.0,
    flavor: 'A última moeda cunhada antes da Queda. Vale mais que o tesouro inteiro de Vael.',
  },

  /* ============ v11 — MÍTICOS & expansão ============ */

  // ---- MÍTICOS (14) — o ápice, acima de lendário. Orçamento de stats
  //      claramente acima dos lendários. Taint brutal (3.2-4.5). ----

  // MÍTICOS — armas (5)
  {
    id: 'myth-weapon-author-quill',
    name: 'A PENA DO AUTOR, MOLHADA EM TINTA SUA',
    rarity: 'mythic',
    slot: 'weapon',
    atkBonus: 130,
    rangeBonus: 1,
    taint: 4.0,
    flavor: 'Quem escreveu o reino também te escreveu. Agora você reescreve — com sangue.',
  },
  {
    id: 'myth-weapon-void-edge',
    name: 'GUME DO VAZIO QUE LÊ DE VOLTA',
    rarity: 'mythic',
    slot: 'weapon',
    atkBonus: 150,
    spdBonus: -2,
    taint: 4.5,
    flavor: 'O Vazio não corta carne. Corta a parte da história onde você existia.',
  },
  {
    id: 'myth-weapon-iron-pact-oath',
    name: 'JURAMENTO DO PACTO DE FERRO',
    rarity: 'mythic',
    slot: 'weapon',
    atkBonus: 120,
    hpBonus: 60,
    taint: 3.6,
    flavor: 'Os sete assinaram com a lâmina. Você é o oitavo — e o último nome cabe.',
  },
  {
    id: 'myth-weapon-drowned-scepter',
    name: 'CETRO DA COROA AFOGADA',
    rarity: 'mythic',
    slot: 'weapon',
    atkBonus: 115,
    rangeBonus: 2,
    moveBonus: 1,
    taint: 3.8,
    flavor: 'O rei afogado ainda segura a outra ponta. Puxe forte; ele não solta de graça.',
  },
  {
    id: 'myth-weapon-active-ash',
    name: 'LÂMINA DE CINZA ATIVA',
    rarity: 'mythic',
    slot: 'weapon',
    atkBonus: 140,
    hpBonus: -30,
    taint: 4.2,
    flavor: 'A cinza não esfriou desde 814. Cada golpe queima um pouco de quem segura.',
  },

  // MÍTICOS — elmos (5)
  {
    id: 'myth-helm-seven-crowns',
    name: 'DIADEMA DAS SETE COROAS FUNDIDAS',
    rarity: 'mythic',
    slot: 'helm',
    hpBonus: 240,
    atkBonus: 30,
    taint: 4.0,
    flavor: 'Sete Underlords, uma cabeça. As outras seis discordam, mas estão dentro do metal.',
  },
  {
    id: 'myth-helm-void-mask',
    name: 'MÁSCARA DO VAZIO QUE OLHA DE VOLTA',
    rarity: 'mythic',
    slot: 'helm',
    hpBonus: 200,
    rangeBonus: 1,
    atkBonus: 20,
    taint: 4.3,
    flavor: 'Você olha pro abismo. O Leitor olha pra você. Empate técnico.',
  },
  {
    id: 'myth-helm-drowned-crown',
    name: 'A COROA AFOGADA, ESCORRENDO AINDA',
    rarity: 'mythic',
    slot: 'helm',
    hpBonus: 260,
    moveBonus: -1,
    taint: 4.1,
    flavor: 'A original das originais. Pesa como o mar inteiro. Você respira água agora — detalhe menor.',
  },
  {
    id: 'myth-helm-author-eye',
    name: 'OLHO DO AUTOR ADORMECIDO',
    rarity: 'mythic',
    slot: 'helm',
    hpBonus: 180,
    atkBonus: 40,
    spdBonus: 1,
    taint: 3.9,
    flavor: 'Vê cada página antes de ser escrita. Inclusive a sua última. Spoiler: dói.',
  },
  {
    id: 'myth-helm-ash-mitra',
    name: 'MITRA DE CINZA ATIVA',
    rarity: 'mythic',
    slot: 'helm',
    hpBonus: 220,
    atkBonus: 25,
    taint: 4.2,
    flavor: 'Coroa um cadáver e ele se levanta achando que ainda manda. Funciona com você também.',
  },

  // MÍTICOS — berloques (4)
  {
    id: 'myth-trinket-void-heart',
    name: 'CORAÇÃO DO VAZIO ENGOLIDO',
    rarity: 'mythic',
    slot: 'trinket',
    hpBonus: 140,
    atkBonus: 45,
    rangeBonus: 1,
    taint: 4.4,
    flavor: 'Bate uma vez. Apaga um reino. Bate de novo. Apaga você um pouquinho.',
  },
  {
    id: 'myth-trinket-readers-bookmark',
    name: 'O MARCADOR DO LEITOR',
    rarity: 'mythic',
    slot: 'trinket',
    atkBonus: 50,
    spdBonus: 3,
    moveBonus: 2,
    taint: 3.7,
    flavor: 'Marca a página onde você morre. Enquanto o Leitor não voltar, você não morre. Reze pra distração dele.',
  },
  {
    id: 'myth-trinket-iron-pact-seal',
    name: 'SELO INTEIRO DO PACTO DE FERRO',
    rarity: 'mythic',
    slot: 'trinket',
    hpBonus: 120,
    atkBonus: 55,
    spdBonus: 1,
    taint: 4.0,
    flavor: 'Os sete selos juntos. Quem reúne os sete vira o oitavo. Ninguém viveu pra contar o nono.',
  },
  {
    id: 'myth-trinket-final-ember',
    name: 'A ÚLTIMA BRASA DE 814',
    rarity: 'mythic',
    slot: 'trinket',
    hpBonus: 160,
    atkBonus: 40,
    moveBonus: -1,
    taint: 3.5,
    flavor: 'A faísca que queimou o mundo velho. Guarde no bolso. Não é como se piorasse.',
  },

  // ---- EXPANSÃO MID-GAME (10) — common → legendary ----
  {
    id: 'v11-common-tin-spoon',
    name: 'COLHER DE LATA AFIADA',
    rarity: 'common',
    slot: 'weapon',
    atkBonus: 7,
    taint: 0,
    flavor: 'Amolada na pedra errada. Ainda assim, mais letal que a maioria dos refeitórios.',
  },
  {
    id: 'v11-common-rag-hood',
    name: 'CAPUZ DE TRAPO MOFADO',
    rarity: 'common',
    slot: 'helm',
    hpBonus: 18,
    spdBonus: 1,
    taint: 0,
    flavor: 'Cheira a porão. Disfarça que você também.',
  },
  {
    id: 'v11-uncommon-quarry-maul',
    name: 'MARRETA DA PEDREIRA',
    rarity: 'uncommon',
    slot: 'weapon',
    atkBonus: 18,
    spdBonus: -1,
    taint: 0.3,
    flavor: 'Quebrou mil pedras e dois capatazes. Não conta os capatazes.',
  },
  {
    id: 'v11-uncommon-tax-ledger',
    name: 'LIVRO-CAIXA DO COLETOR',
    rarity: 'uncommon',
    slot: 'trinket',
    hpBonus: 25,
    moveBonus: 1,
    taint: 0.4,
    flavor: 'Cada nome riscado era alguém que não pagou. Agora ninguém paga, ninguém respira.',
  },
  {
    id: 'v11-cursed-leech-blade',
    name: 'LÂMINA SANGUESSUGA',
    rarity: 'cursed',
    slot: 'weapon',
    atkBonus: 28,
    hpBonus: 20,
    taint: 0.9,
    flavor: 'Bebe do inimigo. Quando não tem inimigo, ela tem sede. Você sabe quem está por perto.',
  },
  {
    id: 'v11-cursed-whisper-veil',
    name: 'VÉU DOS SUSSURROS',
    rarity: 'cursed',
    slot: 'helm',
    hpBonus: 55,
    spdBonus: 1,
    taint: 1.0,
    flavor: 'Os mortos te contam segredos. Em troca, só querem que você não pare de matar.',
  },
  {
    id: 'v11-cursed-jealous-eye',
    name: 'OLHO INVEJOSO',
    rarity: 'cursed',
    slot: 'trinket',
    atkBonus: 12,
    rangeBonus: 1,
    spdBonus: 1,
    taint: 1.1,
    flavor: 'Cobiça tudo o que vê. Felizmente, o que ele vê tende a morrer.',
  },
  {
    id: 'v11-relic-gallows-rope',
    name: 'CORDA DA FORCA REAL',
    rarity: 'relic',
    slot: 'trinket',
    hpBonus: 60,
    atkBonus: 18,
    taint: 1.7,
    flavor: 'Enforcou três reis e um inocente. O inocente foi engano. Os reis, não.',
  },
  {
    id: 'v11-relic-warden-helm',
    name: 'ELMO DO CARCEREIRO',
    rarity: 'relic',
    slot: 'helm',
    hpBonus: 95,
    atkBonus: 10,
    taint: 1.5,
    flavor: 'Guardou a masmorra por quarenta anos. Agora guarda você — de dentro pra fora.',
  },
  {
    id: 'v11-legendary-debt-blade',
    name: 'LÂMINA DA DÍVIDA IMPAGÁVEL',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 85,
    spdBonus: 1,
    taint: 2.6,
    flavor: 'Cobra o que o reino deve a você. O reino discorda. A lâmina não aceita "não".',
  },

  /* ============ v12 — MAIS ESPÓLIO ============ */

  // ---- COMMON (10) ----
  {
    id: 'v12-common-bent-fork',
    name: 'GARFO TORTO DE TAVERNA',
    rarity: 'common',
    slot: 'weapon',
    atkBonus: 6,
    taint: 0,
    flavor: 'Três dentes. Um deles ainda tem cebola de 814. A cebola também não perdoa.',
  },
  {
    id: 'v12-common-cobble-club',
    name: 'PORRETE DE PARALELEPÍPEDO',
    rarity: 'common',
    slot: 'weapon',
    atkBonus: 9,
    spdBonus: -1,
    taint: 0,
    flavor: 'Arrancou da rua principal de Vael. A rua não vai sentir falta; já está afundada.',
  },
  {
    id: 'v12-common-splinter-shiv',
    name: 'ESTILETE DE LASCA',
    rarity: 'common',
    slot: 'weapon',
    atkBonus: 8,
    spdBonus: 1,
    taint: 0,
    flavor: 'Lasca do portão do castelo. Pequena, mas guarda rancor de portão inteiro.',
  },
  {
    id: 'v12-common-bucket-helm',
    name: 'BALDE FURADO REAPROVEITADO',
    rarity: 'common',
    slot: 'helm',
    hpBonus: 16,
    taint: 0,
    flavor: 'O furo é exatamente na altura do olho. Coincidência reconfortante.',
  },
  {
    id: 'v12-common-felt-cap',
    name: 'BARRETE DE FELTRO ENCHARCADO',
    rarity: 'common',
    slot: 'helm',
    hpBonus: 14,
    spdBonus: 1,
    taint: 0,
    flavor: 'Secou no varal de um enforcado. Ainda goteja. Você se acostuma — todo mundo se acostuma.',
  },
  {
    id: 'v12-common-tin-circlet',
    name: 'AROZINHO DE LATA',
    rarity: 'common',
    slot: 'helm',
    hpBonus: 20,
    taint: 0,
    flavor: 'Vendido como "coroa de iniciante" na feira. O vendedor riu. Você ainda está na partida; ele não.',
  },
  {
    id: 'v12-common-lucky-tooth',
    name: 'DENTE DA SORTE DE OUTRO',
    rarity: 'common',
    slot: 'trinket',
    moveBonus: 1,
    taint: 0,
    flavor: 'Deu muita sorte pro dono anterior. Até a parte em que perdeu o dente.',
  },
  {
    id: 'v12-common-rat-pelt',
    name: 'TRAPO DE PELE DE RATO',
    rarity: 'common',
    slot: 'trinket',
    hpBonus: 8,
    spdBonus: 1,
    taint: 0,
    flavor: 'O rato sobreviveu à Queda de 814. Mais resistente que a maioria dos nobres.',
  },
  {
    id: 'v12-common-cracked-whistle',
    name: 'APITO RACHADO DO VIGIA',
    rarity: 'common',
    slot: 'trinket',
    spdBonus: 1,
    moveBonus: 1,
    taint: 0,
    flavor: 'Não apita mais. O vigia também não. Pelo menos um dos dois ainda é útil.',
  },
  {
    id: 'v12-common-soup-ladle',
    name: 'CONCHA DE SOPA DO REFEITÓRIO',
    rarity: 'common',
    slot: 'weapon',
    atkBonus: 11,
    taint: 0,
    flavor: 'Serviu mil tigelas e quebrou um nariz. Adivinha qual é lembrado com carinho.',
  },

  // ---- UNCOMMON (10) ----
  {
    id: 'v12-uncommon-gravedigger-spade',
    name: 'PÁ DO COVEIRO MADRUGADOR',
    rarity: 'uncommon',
    slot: 'weapon',
    atkBonus: 22,
    taint: 0.3,
    flavor: 'Cava covas mais rápido do que você as enche. E você enche bastante.',
  },
  {
    id: 'v12-uncommon-cinder-rake',
    name: 'ANCINHO DE CINZAS MORNAS',
    rarity: 'uncommon',
    slot: 'weapon',
    atkBonus: 28,
    spdBonus: -1,
    taint: 0.4,
    flavor: 'Junta as cinzas que ainda não viraram cinza ativa. Por enquanto.',
  },
  {
    id: 'v12-uncommon-tide-glaive',
    name: 'FOICE-MARÉ DO DOCA',
    rarity: 'uncommon',
    slot: 'weapon',
    atkBonus: 20,
    rangeBonus: 1,
    taint: 0.4,
    flavor: 'Do porto que afundou junto com a coroa. Ainda corta com gosto de sal.',
  },
  {
    id: 'v12-uncommon-watchman-barbut',
    name: 'CELADA DO GUARDA NOTURNO',
    rarity: 'uncommon',
    slot: 'helm',
    hpBonus: 38,
    taint: 0.3,
    flavor: 'O guarda jurou vigiar até o amanhecer. Em 814, o amanhecer cancelou.',
  },
  {
    id: 'v12-uncommon-scholar-hood',
    name: 'CAPELO DO ESCRIBA CENSURADO',
    rarity: 'uncommon',
    slot: 'helm',
    hpBonus: 30,
    rangeBonus: 1,
    taint: 0.5,
    flavor: 'Copiou a história oficial. Depois copiou a verdadeira. Sobrou a cabeça; faltou o pescoço.',
  },
  {
    id: 'v12-uncommon-rebar-coif',
    name: 'COIFA DE VERGALHÃO',
    rarity: 'uncommon',
    slot: 'helm',
    hpBonus: 44,
    moveBonus: -1,
    taint: 0.4,
    flavor: 'Tirada das ruínas do banco-estado. Protege o crânio melhor do que protegeu o império.',
  },
  {
    id: 'v12-uncommon-collector-ring',
    name: 'ANEL DE SINETE DO AGIOTA',
    rarity: 'uncommon',
    slot: 'trinket',
    atkBonus: 16,
    spdBonus: 1,
    taint: 0.5,
    flavor: 'Carimbava promissórias. Agora carimba caveiras. O juro continua absurdo.',
  },
  {
    id: 'v12-uncommon-spark-fetish',
    name: 'FETICHE DE FAÍSCA',
    rarity: 'uncommon',
    slot: 'trinket',
    atkBonus: 14,
    rangeBonus: 1,
    taint: 0.5,
    flavor: 'Uma gota de raio engarrafada por um louco. O louco vendeu barato — antes de evaporar.',
  },
  {
    id: 'v12-uncommon-merchant-tongue',
    name: 'AMULETO DA LÍNGUA-DE-MERCADOR',
    rarity: 'uncommon',
    slot: 'trinket',
    hpBonus: 28,
    moveBonus: 1,
    taint: 0.4,
    flavor: 'Convence qualquer um de qualquer coisa. Convenceu até a morte a esperar um pouco.',
  },
  {
    id: 'v12-uncommon-iron-knuckles',
    name: 'SOQUEIRAS DA GREVE DE 814',
    rarity: 'uncommon',
    slot: 'weapon',
    atkBonus: 25,
    spdBonus: 1,
    taint: 0.5,
    flavor: 'Os operários exigiram pão. Receberam cinzas. Guardaram as soqueiras pra você.',
  },

  // ---- CURSED (10) ----
  {
    id: 'v12-cursed-thirst-scimitar',
    name: 'CIMITARRA DA SEDE PERPÉTUA',
    rarity: 'cursed',
    slot: 'weapon',
    atkBonus: 42,
    hpBonus: 15,
    taint: 0.9,
    flavor: 'Bebe sangue e nunca sacia. Nos dias bons, é do inimigo. Nos outros, é só sangue.',
  },
  {
    id: 'v12-cursed-stormtooth',
    name: 'DENTE-DE-TEMPESTADE',
    rarity: 'cursed',
    slot: 'weapon',
    atkBonus: 50,
    spdBonus: -1,
    taint: 1.0,
    flavor: 'Cada golpe solta um raiozinho. Você acerta o inimigo. O raio, às vezes, acerta você.',
  },
  {
    id: 'v12-cursed-regret-edge',
    name: 'GUME DO ARREPENDIMENTO TARDIO',
    rarity: 'cursed',
    slot: 'weapon',
    atkBonus: 38,
    rangeBonus: 1,
    taint: 1.1,
    flavor: 'Sussurra o nome de cada um que você cortou. A lista cresce mais rápido que a memória.',
  },
  {
    id: 'v12-cursed-leech-helm',
    name: 'ELMO SANGUESSUGA',
    rarity: 'cursed',
    slot: 'helm',
    hpBonus: 65,
    atkBonus: 8,
    taint: 1.0,
    flavor: 'Drena a vitalidade dos caídos pra dentro do seu crânio. O crânio não pediu, mas aceita.',
  },
  {
    id: 'v12-cursed-mirror-mask',
    name: 'MÁSCARA-ESPELHO RACHADA',
    rarity: 'cursed',
    slot: 'helm',
    hpBonus: 52,
    rangeBonus: 1,
    taint: 1.1,
    flavor: 'Reflete o inimigo. E também reflete o que você está virando. Não olhe muito tempo.',
  },
  {
    id: 'v12-cursed-tithe-crown',
    name: 'COROA DO DÍZIMO DE SANGUE',
    rarity: 'cursed',
    slot: 'helm',
    hpBonus: 70,
    atkBonus: 10,
    moveBonus: -1,
    taint: 1.2,
    flavor: 'Coletava dez por cento de cada súdito. Agora coleta dez por cento de cada respiração sua.',
  },
  {
    id: 'v12-cursed-spite-eye',
    name: 'OLHO DO RANCOR DESTILADO',
    rarity: 'cursed',
    slot: 'trinket',
    atkBonus: 22,
    rangeBonus: 1,
    spdBonus: 1,
    taint: 1.1,
    flavor: 'Enxerga a fraqueza alheia com clareza ofensiva. A sua, ele educadamente ignora.',
  },
  {
    id: 'v12-cursed-debt-locket',
    name: 'RELICÁRIO DA DÍVIDA DE SANGUE',
    rarity: 'cursed',
    slot: 'trinket',
    hpBonus: 48,
    atkBonus: 14,
    taint: 1.2,
    flavor: 'Guarda uma mecha de cabelo de cada credor que você "quitou". Está ficando pesado.',
  },
  {
    id: 'v12-cursed-storm-charm',
    name: 'BERLOQUE DO RAIO ENGAIOLADO',
    rarity: 'cursed',
    slot: 'trinket',
    atkBonus: 26,
    spdBonus: 1,
    rangeBonus: 1,
    taint: 1.3,
    flavor: 'Um raio preso numa gaiola de prata. Ele quer sair. Você quer que ele saia — no inimigo.',
  },
  {
    id: 'v12-cursed-void-whisper-blade',
    name: 'LÂMINA DO SUSSURRO DO VAZIO',
    rarity: 'cursed',
    slot: 'weapon',
    atkBonus: 55,
    hpBonus: -15,
    taint: 1.3,
    flavor: 'O Vazio sussurra que você é só uma frase num livro. A lâmina concorda e corta mais fundo.',
  },

  // ---- RELIC (10) ----
  {
    id: 'v12-relic-bleeding-falchion',
    name: 'BRAQUEMARTE QUE SANGRA SOZINHO',
    rarity: 'relic',
    slot: 'weapon',
    atkBonus: 62,
    taint: 1.5,
    flavor: 'Sangra mesmo sem ferida. Os médicos do reino desistiram; você só limpa de vez em quando.',
  },
  {
    id: 'v12-relic-thunder-warpike',
    name: 'CHUÇO DO TROVÃO COROADO',
    rarity: 'relic',
    slot: 'weapon',
    atkBonus: 56,
    rangeBonus: 1,
    spdBonus: 1,
    taint: 1.7,
    flavor: 'Cada estocada estala como tempestade. Os heróis confundem com presságio. Estão certos.',
  },
  {
    id: 'v12-relic-aegis-cleaver',
    name: 'CUTELO-ÉGIDE DO PRETORIANO',
    rarity: 'relic',
    slot: 'weapon',
    atkBonus: 58,
    hpBonus: 35,
    taint: 1.8,
    flavor: 'Era escudo. Viraram lâmina. O pretoriano protestou — uma só vez, em voz baixa.',
  },
  {
    id: 'v12-relic-drowned-greathelm',
    name: 'ELMO PESADO DA GUARDA AFOGADA',
    rarity: 'relic',
    slot: 'helm',
    hpBonus: 100,
    moveBonus: -1,
    taint: 1.6,
    flavor: 'Os guardas afundaram com a coroa, fiéis até o fundo. O elmo subiu sozinho. Procurando cabeça.',
  },
  {
    id: 'v12-relic-ashen-diadem',
    name: 'DIADEMA DE CINZA ASSENTADA',
    rarity: 'relic',
    slot: 'helm',
    hpBonus: 85,
    atkBonus: 18,
    taint: 1.9,
    flavor: 'A cinza ainda não está ativa. "Ainda" é a palavra mais cara do reino.',
  },
  {
    id: 'v12-relic-storm-barbute',
    name: 'CELADA DO PORTADOR DE RAIOS',
    rarity: 'relic',
    slot: 'helm',
    hpBonus: 80,
    spdBonus: 2,
    atkBonus: 12,
    taint: 1.8,
    flavor: 'Atrai raios. Você sobrevive. Quem está atrás de você, estatística incerta.',
  },
  {
    id: 'v12-relic-author-margin-note',
    name: 'NOTA DE MARGEM DO AUTOR',
    rarity: 'relic',
    slot: 'trinket',
    atkBonus: 28,
    rangeBonus: 2,
    taint: 2.0,
    flavor: 'Uma anotação que o Autor deixou na sua página: "este sobrevive mais do que eu planejei".',
  },
  {
    id: 'v12-relic-aegis-sigil',
    name: 'SIGILO DA ÉGIDE PARTIDA',
    rarity: 'relic',
    slot: 'trinket',
    hpBonus: 75,
    atkBonus: 15,
    taint: 1.7,
    flavor: 'Metade de um escudo lendário. A outra metade está cravada em quem tentou ficar com as duas.',
  },
  {
    id: 'v12-relic-throne-shard',
    name: 'ESTILHAÇO DO TRONO FRANQUEADO',
    rarity: 'relic',
    slot: 'trinket',
    atkBonus: 22,
    hpBonus: 55,
    moveBonus: 1,
    taint: 1.9,
    flavor: 'Caco do trono que virou franquia em sete cidades-estado. Cada filial faliu. O caco prospera.',
  },
  {
    id: 'v12-relic-warden-greataxe',
    name: 'GRANDE MACHADO DO CARCEREIRO-MOR',
    rarity: 'relic',
    slot: 'weapon',
    atkBonus: 68,
    spdBonus: -1,
    taint: 1.8,
    flavor: 'Mantinha a ordem na masmorra real com um argumento de dois gumes. Ninguém recorria.',
  },

  // ---- LEGENDARY (9) ----
  {
    id: 'v12-legendary-bleedstorm-blade',
    name: 'LÂMINA DA TEMPESTADE-DE-SANGUE',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 95,
    rangeBonus: 1,
    taint: 2.7,
    flavor: 'Cada corte chama um raio que abre outro corte. O ciclo só termina quando o inimigo termina.',
  },
  {
    id: 'v12-legendary-franchise-scepter',
    name: 'CETRO DAS SETE FRANQUIAS CAÍDAS',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 78,
    hpBonus: 45,
    taint: 2.8,
    flavor: 'Sete cidades-estado licenciaram a coroa. Sete faliram. O cetro coletou a multa de todas.',
  },
  {
    id: 'v12-legendary-readers-quill-dagger',
    name: 'ESTILETE-PENA DO LEITOR DISTRAÍDO',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 72,
    spdBonus: 2,
    moveBonus: 1,
    taint: 2.9,
    flavor: 'Enquanto o Leitor não vira a página, você corta mais rápido que a narração consegue descrever.',
  },
  {
    id: 'v12-legendary-tidecrown-greathelm',
    name: 'ELMO DA MARÉ COROADA',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 160,
    atkBonus: 15,
    taint: 2.9,
    flavor: 'Trazido do fundo onde a coroa afundou. Pulmões opcionais a partir de agora.',
  },
  {
    id: 'v12-legendary-stormwrought-crown',
    name: 'COROA FORJADA EM TEMPESTADE',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 120,
    spdBonus: 2,
    atkBonus: 20,
    taint: 3.0,
    flavor: 'Cunhada no olho de um furacão por um ferreiro que não voltou. Vale cada watt de morte.',
  },
  {
    id: 'v12-legendary-ashen-warmask',
    name: 'MÁSCARA-DE-GUERRA DE CINZA ATIVA',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 135,
    atkBonus: 30,
    moveBonus: -1,
    taint: 3.1,
    flavor: 'A cinza acordou. Ela acha que você é o reino velho que ela queimou. Não a corrija.',
  },
  {
    id: 'v12-legendary-author-bookmark',
    name: 'O MARCADOR DO AUTOR ESQUECIDO',
    rarity: 'legendary',
    slot: 'trinket',
    atkBonus: 35,
    hpBonus: 90,
    rangeBonus: 1,
    taint: 2.9,
    flavor: 'O Autor marcou aqui antes de dormir. Enquanto não acordar, sua história não acaba.',
  },
  {
    id: 'v12-legendary-bleeding-aegis',
    name: 'ÉGIDE QUE SANGRA POR VOCÊ',
    rarity: 'legendary',
    slot: 'trinket',
    hpBonus: 110,
    atkBonus: 25,
    taint: 2.8,
    flavor: 'Recebe as feridas que seriam suas. Em troca, sangra o tempo todo, baixinho, com lealdade.',
  },
  {
    id: 'v12-legendary-void-ledger',
    name: 'O LIVRO-CAIXA DO VAZIO',
    rarity: 'legendary',
    slot: 'trinket',
    atkBonus: 40,
    spdBonus: 1,
    hpBonus: -10,
    taint: 3.1,
    flavor: 'Anota tudo o que o Vazio engoliu. Seu nome está numa linha lá embaixo, ainda a lápis.',
  },

  // ---- MYTHIC (6) — o ápice. Taint 3.2-4.8, orçamento brutal. ----
  {
    id: 'v12-myth-weapon-bleeding-author',
    name: 'GUME DO AUTOR QUE SANGRA A PÁGINA',
    rarity: 'mythic',
    slot: 'weapon',
    atkBonus: 155,
    rangeBonus: 1,
    hpBonus: -40,
    taint: 4.6,
    flavor: 'Corta a frase em que você nasceu. A tinta escorre vermelha. O Autor finge que não notou.',
  },
  {
    id: 'v12-myth-weapon-stormcrown-edge',
    name: 'LÂMINA DA COROA-TEMPESTADE',
    rarity: 'mythic',
    slot: 'weapon',
    atkBonus: 135,
    spdBonus: 2,
    rangeBonus: 1,
    taint: 4.0,
    flavor: 'Os sete Underlords morreram tentando empunhá-la sob um céu limpo. Você esperou trovejar.',
  },
  {
    id: 'v12-myth-helm-drowned-author-crown',
    name: 'A COROA AFOGADA DO AUTOR',
    rarity: 'mythic',
    slot: 'helm',
    hpBonus: 270,
    atkBonus: 25,
    moveBonus: -1,
    taint: 4.3,
    flavor: 'O Autor afundou junto com o reino que escreveu. A coroa boiou. Procurando alguém pra terminar o capítulo.',
  },
  {
    id: 'v12-myth-helm-active-ash-diadem',
    name: 'DIADEMA DA CINZA TOTALMENTE ATIVA',
    rarity: 'mythic',
    slot: 'helm',
    hpBonus: 230,
    atkBonus: 45,
    taint: 4.8,
    flavor: 'Toda a cinza de 814, acesa de uma vez, sobre sua testa. Você arde como uma capital. Lindamente.',
  },
  {
    id: 'v12-myth-trinket-readers-final-page',
    name: 'A ÚLTIMA PÁGINA DO LEITOR',
    rarity: 'mythic',
    slot: 'trinket',
    hpBonus: 180,
    atkBonus: 50,
    rangeBonus: 1,
    spdBonus: 1,
    taint: 4.5,
    flavor: 'A página final, ainda em branco. Enquanto o Leitor não a vira, ninguém — nem o Vazio — pode te encerrar.',
  },
  {
    id: 'v12-myth-trinket-eighth-crown-seal',
    name: 'O SELO DA OITAVA COROA',
    rarity: 'mythic',
    slot: 'trinket',
    hpBonus: 150,
    atkBonus: 60,
    spdBonus: 2,
    moveBonus: 1,
    taint: 4.7,
    flavor: 'Sete coroas afundaram. A oitava é forjada de tudo o que sobrou — inclusive de você. Use enquanto ainda há "você".',
  },

  /* ============ v13b — ESTOQUE DO MERCANTE ============ */

  // ---- COMMON (9) — saldão do mercante, qualidade duvidosa ----
  {
    id: 'v13b-common-clearance-shiv',
    name: 'FACA "TUDO POR 1 MOEDA"',
    rarity: 'common',
    slot: 'weapon',
    atkBonus: 6,
    taint: 0,
    flavor: 'Etiqueta do mercante ainda colada no cabo. Ele jura que afia sozinha. Não afia.',
  },
  {
    id: 'v13b-common-promo-mace',
    name: 'CLAVA DE BRINDE PROMOCIONAL',
    rarity: 'common',
    slot: 'weapon',
    atkBonus: 10,
    spdBonus: -1,
    taint: 0,
    flavor: 'Grátis na compra de duas adagas. As duas adagas quebraram. A clava aguenta.',
  },
  {
    id: 'v13b-common-knockoff-blade',
    name: 'RÉPLICA "BRYANNICA" (NÃO OFICIAL)',
    rarity: 'common',
    slot: 'weapon',
    atkBonus: 9,
    taint: 0,
    flavor: 'Grita "BRY-" e engasga. O mercante diz que é "recurso de áudio limitado".',
  },
  {
    id: 'v13b-common-dented-kettle',
    name: 'CHALEIRA AMASSADA DE GUERRA',
    rarity: 'common',
    slot: 'helm',
    hpBonus: 15,
    taint: 0,
    flavor: 'Ainda assobia quando você corre. Avisa o inimigo, mas mantém o chá quente.',
  },
  {
    id: 'v13b-common-display-helm',
    name: 'ELMO DE VITRINE (SEM FUNDO)',
    rarity: 'common',
    slot: 'helm',
    hpBonus: 17,
    spdBonus: 1,
    taint: 0,
    flavor: 'Modelo de exposição. Protege a parte da frente da cabeça. A de trás é "sob encomenda".',
  },
  {
    id: 'v13b-common-foam-circlet',
    name: 'COROA DE ESPUMA DE FEIRA',
    rarity: 'common',
    slot: 'helm',
    hpBonus: 12,
    moveBonus: 1,
    taint: 0,
    flavor: 'Dão de graça pra quem comprou ingresso do torneio. Leve. Inútil. Querida.',
  },
  {
    id: 'v13b-common-loyalty-token',
    name: 'FICHA DE FIDELIDADE DO MERCANTE',
    rarity: 'common',
    slot: 'trinket',
    spdBonus: 1,
    taint: 0,
    flavor: 'Junte dez e ganhe um chá. Você está no zero. Sempre esteve.',
  },
  {
    id: 'v13b-common-expired-charm',
    name: 'AMULETO COM VALIDADE VENCIDA',
    rarity: 'common',
    slot: 'trinket',
    hpBonus: 9,
    taint: 0,
    flavor: 'Vencido desde 814. O mercante diz que "encantamento não estraga". O mercante mente.',
  },
  {
    id: 'v13b-common-receipt-fetish',
    name: 'FETICHE DE NOTA FISCAL DOBRADA',
    rarity: 'common',
    slot: 'trinket',
    spdBonus: 1,
    moveBonus: 1,
    taint: 0,
    flavor: 'Comprovante de uma compra que o mercante nega ter feito. Dá sorte por puro rancor.',
  },

  // ---- UNCOMMON (9) ----
  {
    id: 'v13b-uncommon-haggle-saber',
    name: 'SABRE DA PECHINCHA AGRESSIVA',
    rarity: 'uncommon',
    slot: 'weapon',
    atkBonus: 21,
    taint: 0.3,
    flavor: 'O mercante baixou o preço três vezes. A lâmina baixa a guarda do inimigo de uma só.',
  },
  {
    id: 'v13b-uncommon-restock-hatchet',
    name: 'MACHADINHA DE REPOSIÇÃO',
    rarity: 'uncommon',
    slot: 'weapon',
    atkBonus: 24,
    spdBonus: 1,
    taint: 0.4,
    flavor: 'Sempre tem outra no estoque. O mercante nunca explica de onde vêm. Você não pergunta.',
  },
  {
    id: 'v13b-uncommon-sparkwire-spear',
    name: 'LANÇA DE FIO ENERGIZADO',
    rarity: 'uncommon',
    slot: 'weapon',
    atkBonus: 19,
    rangeBonus: 1,
    taint: 0.4,
    flavor: 'Um fiapo de raio enrolado na ponta. Estala feio. O selo de garantia já estava rompido.',
  },
  {
    id: 'v13b-uncommon-counter-coif',
    name: 'COIFA DO BALCONISTA VETERANO',
    rarity: 'uncommon',
    slot: 'helm',
    hpBonus: 36,
    taint: 0.3,
    flavor: 'Quarenta anos atrás de um balcão sem levar um soco. Até hoje. A coifa aprendeu a aparar.',
  },
  {
    id: 'v13b-uncommon-inventory-hood',
    name: 'CAPUZ DO CONFERENTE DE ESTOQUE',
    rarity: 'uncommon',
    slot: 'helm',
    hpBonus: 30,
    rangeBonus: 1,
    taint: 0.5,
    flavor: 'Contou cada item do depósito do mercante. Inclusive os que não deviam existir. Por isso o capuz tampa os olhos.',
  },
  {
    id: 'v13b-uncommon-bargain-barbut',
    name: 'CELADA DO LIQUIDA-TUDO',
    rarity: 'uncommon',
    slot: 'helm',
    hpBonus: 42,
    moveBonus: -1,
    taint: 0.4,
    flavor: 'Pesada porque vem cheia de "brindes" que você não pediu. O mercante chama de valor agregado.',
  },
  {
    id: 'v13b-uncommon-coin-charm',
    name: 'BERLOQUE DO TROCO ESQUECIDO',
    rarity: 'uncommon',
    slot: 'trinket',
    atkBonus: 15,
    spdBonus: 1,
    taint: 0.5,
    flavor: 'Feito das moedinhas que o mercante "esqueceu" de devolver. Vingança rende juros.',
  },
  {
    id: 'v13b-uncommon-warranty-seal',
    name: 'SELO DE GARANTIA ESTENDIDA',
    rarity: 'uncommon',
    slot: 'trinket',
    hpBonus: 26,
    moveBonus: 1,
    taint: 0.4,
    flavor: 'Cobre defeitos de fabricação. Não cobre flechas, espadas, maldições, nem o Vazio. Leia as letras miúdas.',
  },
  {
    id: 'v13b-uncommon-sample-vial',
    name: 'FRASCO DE AMOSTRA GRÁTIS',
    rarity: 'uncommon',
    slot: 'trinket',
    atkBonus: 13,
    rangeBonus: 1,
    taint: 0.5,
    flavor: 'Cheirinho de cinza ainda morna. "Experimente antes de comprar", disse o mercante. Você experimentou. Agora compra sempre.',
  },

  // ---- CURSED (9) ----
  {
    id: 'v13b-cursed-layaway-cleaver',
    name: 'CUTELO DO CREDIÁRIO ETERNO',
    rarity: 'cursed',
    slot: 'weapon',
    atkBonus: 40,
    hpBonus: 12,
    taint: 0.9,
    flavor: 'Parcelado em vidas. O mercante cobra a primeira agora. As outras, "quando der".',
  },
  {
    id: 'v13b-cursed-stormreturn-blade',
    name: 'LÂMINA DA TROCA SEM NOTA',
    rarity: 'cursed',
    slot: 'weapon',
    atkBonus: 48,
    spdBonus: -1,
    taint: 1.0,
    flavor: 'Solta um raio que às vezes volta pro vendedor. Por isso o mercante não aceita devolução.',
  },
  {
    id: 'v13b-cursed-bleed-dagger',
    name: 'ADAGA DA AMOSTRA QUE NÃO FECHA',
    rarity: 'cursed',
    slot: 'weapon',
    atkBonus: 36,
    rangeBonus: 1,
    taint: 1.1,
    flavor: 'O corte que ela abre nunca cicatriza — nem no inimigo, nem no balcão onde testaram.',
  },
  {
    id: 'v13b-cursed-overstock-helm',
    name: 'ELMO DO EXCESSO DE ESTOQUE',
    rarity: 'cursed',
    slot: 'helm',
    hpBonus: 62,
    atkBonus: 8,
    taint: 1.0,
    flavor: 'O mercante tinha mil. Vendeu novecentos. Os outros cem sussurram pedindo um dono.',
  },
  {
    id: 'v13b-cursed-mirror-display',
    name: 'CAPACETE-ESPELHO DE PROVADOR',
    rarity: 'cursed',
    slot: 'helm',
    hpBonus: 56,
    rangeBonus: 1,
    taint: 1.1,
    flavor: 'Reflete como você ficaria com o item. E como você ficou depois de usá-lo. Os dois não combinam.',
  },
  {
    id: 'v13b-cursed-hostage-crown',
    name: 'COROA DO CLIENTE REFÉM',
    rarity: 'cursed',
    slot: 'helm',
    hpBonus: 68,
    atkBonus: 10,
    moveBonus: -1,
    taint: 1.2,
    flavor: 'Depois que você experimenta, não consegue mais sair da loja. O mercante chama de fidelização.',
  },
  {
    id: 'v13b-cursed-debt-eye',
    name: 'OLHO DO CADASTRO DE INADIMPLENTES',
    rarity: 'cursed',
    slot: 'trinket',
    atkBonus: 20,
    rangeBonus: 1,
    spdBonus: 1,
    taint: 1.1,
    flavor: 'Vê quem deve ao mercante. Todo mundo deve ao mercante. Inclusive os seis Underlords anteriores.',
  },
  {
    id: 'v13b-cursed-loyalty-locket',
    name: 'RELICÁRIO DO PROGRAMA DE PONTOS',
    rarity: 'cursed',
    slot: 'trinket',
    hpBonus: 46,
    atkBonus: 14,
    taint: 1.2,
    flavor: 'Acumula um ponto por inimigo abatido. A recompensa final, o mercante garante, "vale a pena". Ninguém resgatou ainda.',
  },
  {
    id: 'v13b-cursed-void-coupon',
    name: 'CUPOM DE DESCONTO DO VAZIO',
    rarity: 'cursed',
    slot: 'trinket',
    atkBonus: 24,
    hpBonus: -14,
    taint: 1.3,
    flavor: 'Vinte por cento de desconto na sua própria existência. O Vazio aceita. O mercante carimba sorrindo.',
  },

  // ---- RELIC (8) ----
  {
    id: 'v13b-relic-flagship-falchion',
    name: 'BRAQUEMARTE CARRO-CHEFE',
    rarity: 'relic',
    slot: 'weapon',
    atkBonus: 64,
    taint: 1.5,
    flavor: 'O item da vitrine que o mercante nunca vende de verdade. Você levou. Ele ainda não percebeu.',
  },
  {
    id: 'v13b-relic-lightning-warpike',
    name: 'CHUÇO DA OFERTA RELÂMPAGO',
    rarity: 'relic',
    slot: 'weapon',
    atkBonus: 57,
    rangeBonus: 1,
    spdBonus: 1,
    taint: 1.7,
    flavor: 'Promoção por tempo limitado. O tempo limitado é o do inimigo. Cada estocada raia o céu.',
  },
  {
    id: 'v13b-relic-recall-greataxe',
    name: 'MACHADO DO RECALL DE FÁBRICA',
    rarity: 'relic',
    slot: 'weapon',
    atkBonus: 70,
    spdBonus: -1,
    taint: 1.8,
    flavor: 'Recolhido por "decapitar usuários ocasionalmente". O defeito virou o argumento de venda.',
  },
  {
    id: 'v13b-relic-vault-greathelm',
    name: 'ELMO DO COFRE DO MERCANTE',
    rarity: 'relic',
    slot: 'helm',
    hpBonus: 98,
    moveBonus: -1,
    taint: 1.6,
    flavor: 'Forjado da porta do cofre onde ele guarda o que não está à venda. Você abriu. Você levou a porta.',
  },
  {
    id: 'v13b-relic-ashen-display-crown',
    name: 'COROA DE MOSTRUÁRIO DE CINZA',
    rarity: 'relic',
    slot: 'helm',
    hpBonus: 86,
    atkBonus: 17,
    taint: 1.9,
    flavor: 'Exposta sob vidro com a placa "NÃO TOCAR — CINZA AINDA NÃO ATIVA". A placa estava errada.',
  },
  {
    id: 'v13b-relic-storm-barbute-deluxe',
    name: 'CELADA EDIÇÃO TEMPESTADE DELUXE',
    rarity: 'relic',
    slot: 'helm',
    hpBonus: 82,
    spdBonus: 2,
    atkBonus: 11,
    taint: 1.8,
    flavor: 'Versão "deluxe" porque vem com um raio de brinde por dentro. O raio não pediu pra estar ali.',
  },
  {
    id: 'v13b-relic-author-invoice',
    name: 'A FATURA RABISCADA PELO AUTOR',
    rarity: 'relic',
    slot: 'trinket',
    atkBonus: 27,
    rangeBonus: 2,
    taint: 2.0,
    flavor: 'Na margem, o Autor anotou: "cobrar caro deste; ele dura capítulos demais". O mercante engoliu seco.',
  },
  {
    id: 'v13b-relic-bleeding-pricetag',
    name: 'ETIQUETA DE PREÇO QUE SANGRA',
    rarity: 'relic',
    slot: 'trinket',
    hpBonus: 72,
    atkBonus: 16,
    taint: 1.9,
    flavor: 'O número escorre vermelho e muda sozinho. Sempre pra cima. O mercante chama de "preço dinâmico".',
  },

  // ---- LEGENDARY (6) ----
  {
    id: 'v13b-legendary-blackmarket-blade',
    name: 'LÂMINA DO MERCADO NEGRO LACRADO',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 88,
    rangeBonus: 1,
    taint: 2.7,
    flavor: 'Vendida embaixo do balcão, embaixo do reino, embaixo do Vazio. O mercante nega que existe — enquanto te entrega.',
  },
  {
    id: 'v13b-legendary-franchise-warhammer',
    name: 'MARTELO DA FRANQUIA-MESTRA',
    rarity: 'legendary',
    slot: 'weapon',
    atkBonus: 80,
    hpBonus: 42,
    spdBonus: -1,
    taint: 2.9,
    flavor: 'Licenciado pelas sete cidades-estado. Todas faliram. O mercante comprou a marca na liquidação.',
  },
  {
    id: 'v13b-legendary-drowned-flagship-helm',
    name: 'ELMO CARRO-CHEFE DA MARÉ COROADA',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 158,
    atkBonus: 16,
    taint: 2.9,
    flavor: 'O mercante mergulhou pessoalmente até a coroa afogada por causa deste. Voltou rico. Voltou molhado. Voltou diferente.',
  },
  {
    id: 'v13b-legendary-stormwrought-flagship',
    name: 'COROA EDIÇÃO LIMITADA: TEMPESTADE',
    rarity: 'legendary',
    slot: 'helm',
    hpBonus: 128,
    atkBonus: 22,
    spdBonus: 1,
    taint: 3.0,
    flavor: 'Tiragem de sete unidades, uma por Underlord. Seis sumiram com seus donos. Sobrou esta no estoque.',
  },
  {
    id: 'v13b-legendary-readers-receipt',
    name: 'O RECIBO ETERNO DO LEITOR',
    rarity: 'legendary',
    slot: 'trinket',
    atkBonus: 36,
    hpBonus: 88,
    rangeBonus: 1,
    taint: 2.9,
    flavor: 'Enquanto o Leitor não confere o recibo, a transação — e você — não pode ser cancelada. Reze pra fila estar grande.',
  },
  {
    id: 'v13b-legendary-debt-shield-charm',
    name: 'ÉGIDE-AVAL DA DÍVIDA DO MERCANTE',
    rarity: 'legendary',
    slot: 'trinket',
    hpBonus: 112,
    atkBonus: 24,
    spdBonus: -1,
    taint: 2.8,
    flavor: 'Absorve dano como quem absorve juros. Toda ferida evitada vira uma parcela. O mercante anota tudo.',
  },

  // ---- MYTHIC (4) — itens "fora de catálogo" do mercante ----
  {
    id: 'v13b-myth-weapon-final-sale-edge',
    name: 'GUME DA LIQUIDAÇÃO TOTAL',
    rarity: 'mythic',
    slot: 'weapon',
    atkBonus: 148,
    spdBonus: 2,
    hpBonus: -35,
    taint: 4.4,
    flavor: 'Última peça. Quando ela acaba, acaba o estoque, o mercante, o reino e o capítulo. Compre com pressa.',
  },
  {
    id: 'v13b-myth-weapon-active-ash-clearance',
    name: 'LÂMINA DE CINZA ATIVA "QUEIMA DE ESTOQUE"',
    rarity: 'mythic',
    slot: 'weapon',
    atkBonus: 158,
    rangeBonus: 1,
    taint: 4.7,
    flavor: 'O mercante chamou de "queima de estoque". Não era figura de linguagem. A loja ainda arde, lindamente.',
  },
  {
    id: 'v13b-myth-helm-managers-drowned-crown',
    name: 'A COROA AFOGADA DO GERENTE',
    rarity: 'mythic',
    slot: 'helm',
    hpBonus: 265,
    atkBonus: 28,
    moveBonus: -1,
    taint: 4.3,
    flavor: 'Quando o mercante exige "falar com o gerente do reino", é esta coroa que ele veste. O gerente afogou. A coroa boiou.',
  },
  {
    id: 'v13b-myth-trinket-blank-invoice-of-void',
    name: 'A NOTA EM BRANCO DO VAZIO',
    rarity: 'mythic',
    slot: 'trinket',
    hpBonus: 170,
    atkBonus: 52,
    spdBonus: 1,
    rangeBonus: 1,
    taint: 4.6,
    flavor: 'Sem valor preenchido. Enquanto o Vazio não decide o que cobrar por você, ninguém pode te cobrar nada. Nem a morte.',
  },
]

/** Pick `count` items biased by region tier. Higher tier = better drops.
 * If `forceRare` is true, the first item is guaranteed cursed-or-better
 * (pity timer to prevent dry streaks). */
export function rollLoot(
  stage: number,
  count: number,
  forceRare: boolean = false,
): LootItem[] {
  const pool = LOOT_POOL.slice()
  // 5-tier ladder. Stage 14+ unlocks legendaries (boss-tier regions).
  // Earlier stages cap at relic so legendaries feel like a real milestone.
  const tier =
    stage >= 18
      ? ['relic', 'legendary', 'legendary', 'mythic']
      : stage >= 14
        ? ['cursed', 'relic', 'relic', 'legendary']
        : stage >= 12
          ? ['cursed', 'cursed', 'relic']
          : stage >= 8
            ? ['uncommon', 'cursed', 'cursed']
            : stage >= 4
              ? ['common', 'uncommon', 'cursed']
              : ['common', 'common', 'uncommon']
  const out: LootItem[] = []
  for (let i = 0; i < count; i++) {
    let want: LootRarity
    if (forceRare && i === 0) {
      // Pity timer: scale guaranteed rarity with stage tier.
      want =
        stage >= 18
          ? 'mythic'
          : stage >= 14
            ? 'legendary'
            : stage >= 8
              ? 'relic'
              : 'cursed'
    } else {
      want = tier[Math.floor(Math.random() * tier.length)] as LootRarity
    }
    const candidates = pool.filter((p) => p.rarity === want)
    const pick = candidates[Math.floor(Math.random() * candidates.length)]
    if (pick) out.push(pick)
  }
  return out
}

/* ==========================================================
 * v13 — LOOT CHANCE PER AREA + grind.
 *
 * Instead of "every loot-bearing region always drops 2 items by stage
 * tier", each area now has a DROP CHANCE (so wins don't always pay out —
 * you grind) and a biome/stage-weighted RARITY table (so areas feel
 * distinct: iron forges relics, the Void leaks mythics, the crown hoards
 * legendaries). High rarities are deliberately rare weights — the grind.
 * ========================================================== */

export type LootWeights = Partial<Record<LootRarity, number>>

export type LootProfile = {
  /** 0..1 chance that ANY loot drops on a win (the grind gate). */
  chance: number
  /** How many items roll when it does drop. */
  count: number
  /** Rarity weight table for this area. */
  weights: LootWeights
}

/** Per-area loot profile from biome + stage. Pure; no per-region authoring. */
export function regionLootProfile(biome: string, stage: number): LootProfile {
  // Grindy base chance: even late-game wins miss ~1 in 6.
  const chance = Math.max(0.35, Math.min(0.85, 0.4 + stage * 0.018))
  const count = stage >= 24 ? 2 : stage >= 14 ? 2 : 1
  // Stage gates the rarity ladder; high tiers stay low-weight (grind).
  let weights: LootWeights
  if (stage >= 24) weights = { cursed: 7, relic: 11, legendary: 7, mythic: 2 }
  else if (stage >= 18) weights = { cursed: 11, relic: 12, legendary: 5, mythic: 1 }
  else if (stage >= 12) weights = { uncommon: 5, cursed: 15, relic: 7, legendary: 1 }
  else if (stage >= 8) weights = { common: 5, uncommon: 15, cursed: 9, relic: 1 }
  else if (stage >= 4) weights = { common: 15, uncommon: 12, cursed: 3 }
  else weights = { common: 20, uncommon: 6, cursed: 1 }
  // Biome flavor — bias the table so areas drop themed gear.
  const boost: Record<string, LootWeights> = {
    iron: { relic: 5, cursed: 2 },
    void: { mythic: 4, legendary: 4 },
    crown: { legendary: 4, relic: 2 },
    abyss: { relic: 3, mythic: 1 },
    ash: { cursed: 4, legendary: 1 },
    dunes: { relic: 2, legendary: 1 },
    tundra: { cursed: 3, relic: 1 },
    verdant: { uncommon: 4, cursed: 2 },
    moor: { common: 3, uncommon: 3 },
  }
  const b = boost[biome]
  if (b) {
    weights = { ...weights }
    for (const k of Object.keys(b) as LootRarity[]) {
      weights[k] = (weights[k] ?? 0) + (b[k] ?? 0)
    }
  }
  return { chance, count, weights }
}

/** Roll loot from a weighted rarity table. `forceRare` guarantees the first
 * pick is the highest-weighted rare-or-better present (pity / Ascension). */
export function rollLootWeighted(
  weights: LootWeights,
  count: number,
  forceRare: boolean = false,
): LootItem[] {
  const entries = (Object.entries(weights) as [LootRarity, number][]).filter(
    ([, w]) => w > 0,
  )
  const total = entries.reduce((a, [, w]) => a + w, 0)
  if (total <= 0) return []
  const out: LootItem[] = []
  for (let i = 0; i < count; i++) {
    let want: LootRarity = 'common'
    if (forceRare && i === 0) {
      const order: LootRarity[] = ['mythic', 'legendary', 'relic', 'cursed', 'uncommon', 'common']
      want = order.find((r) => (weights[r] ?? 0) > 0) ?? 'common'
    } else {
      let roll = Math.random() * total
      for (const [r, w] of entries) {
        roll -= w
        if (roll <= 0) {
          want = r
          break
        }
      }
    }
    const candidates = LOOT_POOL.filter((p) => p.rarity === want)
    const pick = candidates[Math.floor(Math.random() * candidates.length)]
    if (pick) out.push(pick)
  }
  return out
}

/** Rarities that get a generated artifact image (relic → legendary → mythic). */
export function lootHasImage(rarity: LootRarity): boolean {
  return rarity === 'relic' || rarity === 'legendary' || rarity === 'mythic'
}

export const RARITY_LABEL: Record<LootRarity, string> = {
  common: 'COMUM',
  uncommon: 'INCOMUM',
  cursed: 'AMALDIÇOADO',
  relic: 'RELÍQUIA',
  legendary: 'LENDÁRIO',
  mythic: 'MÍTICO',
}

export const RARITY_TONE: Record<
  LootRarity,
  'foreground' | 'accent' | 'destructive' | 'gold'
> = {
  common: 'foreground',
  uncommon: 'accent',
  cursed: 'destructive',
  relic: 'gold',
  // Legendaries reuse the gold tone for now — they stand out via the
  // "LENDÁRIO" label + a holo border in the loot/inventory UI.
  legendary: 'gold',
  // Mythics also use gold for the chip color but get a prismatic
  // animated holo border (see `.rarity-mythic` in globals.css) so they
  // read as a whole tier above legendary at a glance.
  mythic: 'gold',
}
