/**
 * REGIÕES DE VAEL'THRAND — 61 cenários, 14 estágios, 8 biomas.
 *
 * O grafo é estritamente forward: toda região no estágio N abre ao menos
 * uma no estágio N+1, então não existe "dead end" que travaria o save.
 * O jogo começa com 3 entradas (estágio 1) liberadas — cada uma puxa um
 * ramo independente que reconverge nos estágios 5-7 e finaliza no
 * estágio 14 (A COROA SUBMERSA).
 *
 * `dropsLoot=true` marca picos de campanha — chefões nomeados, ouro e
 * itens dobrados. Os outros cenários pagam ouro + XP + Soulshards (via
 * `lib/underlord/state.ts`), garantindo progresso constante mesmo sem
 * drops.
 */

import type { Region } from './types'

type Seed = Omit<Region, 'links'> & { links: string[] }
const r = (s: Seed): Region => s

export const REGIONS: Region[] = [
  /* =========================== STAGE 1 =========================== */
  r({
    id: 'lichmoor',
    name: 'O LIQUEMOR',
    subtitle: 'Pântano onde os profetas afundam',
    stage: 1,
    biome: 'moor',
    x: 12,
    y: 78,
    links: ['rotwell', 'bog-cathedral', 'reedfen-altar'],
    lore: 'Bryan diz que aqui ele "sentiu o chamado". Bryan sente o chamado em qualquer lugar com sinal.',
    goldReward: 200,
    heroIds: ['bryan'],
    dropsLoot: false,
  }),
  r({
    id: 'putrid-shoals',
    name: 'BAIXIO PUTREFATO',
    subtitle: 'Maré que devolve só pernas',
    stage: 1,
    biome: 'abyss',
    x: 30,
    y: 88,
    links: ['salt-cloister', 'drowned-warden'],
    lore: 'Aqui afundou a primeira frota de paladinos. O mar guardou os capacetes; devolveu o resto em pedaços.',
    goldReward: 210,
    heroIds: ['kevin'],
    dropsLoot: false,
  }),
  r({
    id: 'meat-market',
    name: 'MERCADO DA CARNE',
    subtitle: 'Onde Tyrella audita ossos',
    stage: 1,
    biome: 'iron',
    x: 52,
    y: 84,
    links: ['sermon-fork', 'flesh-foundry'],
    lore: 'Tyrella exige nota fiscal de cada cadáver. O contador morreu primeiro e abriu MEI no inferno.',
    goldReward: 220,
    heroIds: ['tyrella'],
    dropsLoot: false,
  }),

  /* =========================== STAGE 2 =========================== */
  r({
    id: 'rotwell',
    name: 'POÇO PODRE',
    subtitle: 'Cisterna que ainda lembra do batismo',
    stage: 2,
    biome: 'moor',
    x: 6,
    y: 64,
    links: ['hex-orchard', 'wraith-fen'],
    lore: 'A água daqui ainda murmura latim. Ninguém ouve mais — todo mundo que escutou se afogou.',
    goldReward: 240,
    heroIds: ['gandolfini'],
    dropsLoot: false,
  }),
  r({
    id: 'bog-cathedral',
    name: 'CATEDRAL ATOLADA',
    subtitle: 'Sino que toca pra baixo',
    stage: 2,
    biome: 'moor',
    x: 18,
    y: 60,
    links: ['hex-orchard', 'ironreach', 'rootlich'],
    lore: 'A nave inteira deslizou pro lodo. O sino bate enterrado e os fiéis vêm do fundo.',
    goldReward: 260,
    heroIds: ['kevin'],
    dropsLoot: true,
  }),
  r({
    id: 'salt-cloister',
    name: 'CLAUSTRO DE SAL',
    subtitle: 'Monges que choram em escala',
    stage: 2,
    biome: 'abyss',
    x: 26,
    y: 70,
    links: ['tideglass', 'wraith-fen'],
    // v9 — Hold-out objective. The cloister doors slam shut for four
    // rounds; the heroes only need to break through, so the goal is
    // endurance. First "non-rout" the player ever sees.
    objective: { kind: 'survive', rounds: 4 },
    lore: 'Eles fazem voto de silêncio. Quebram quando você chega. Não quebram bem.',
    goldReward: 250,
    heroIds: ['tyrella'],
    dropsLoot: false,
  }),
  r({
    id: 'drowned-warden',
    name: 'GUARDIÃO AFOGADO',
    subtitle: 'Farol que aponta pra dentro',
    stage: 2,
    biome: 'abyss',
    x: 38,
    y: 76,
    links: ['tideglass', 'crab-tide'],
    lore: 'A luz nunca apagou. O guardião também não — só se molhou pra sempre.',
    goldReward: 270,
    heroIds: ['daggor'],
    dropsLoot: false,
  }),
  r({
    id: 'sermon-fork',
    name: 'BIFURCAÇÃO DO SERMÃO',
    subtitle: 'Onde a estrada reza por escolha',
    stage: 2,
    biome: 'iron',
    x: 60,
    y: 76,
    links: ['ironreach', 'pilgrim-pass'],
    // v9 — Surgical strike. Kevin is the standard-bearer; if he falls,
    // Tyrella retreats. Teaches the player that skipping enemies is a
    // valid strategy. (Other heroes can stay alive — only Kevin matters.)
    objective: { kind: 'assassinate', targetHeroId: 'kevin' },
    lore: 'Dois caminhos. Um vai pra capital, o outro pra forja. Ambos cobram pedágio.',
    goldReward: 280,
    heroIds: ['kevin', 'tyrella'],
    dropsLoot: false,
  }),
  r({
    id: 'flesh-foundry',
    name: 'FUNDIÇÃO DE CARNE',
    subtitle: 'Forja onde o aço grita',
    stage: 2,
    biome: 'iron',
    x: 70,
    y: 80,
    links: ['pilgrim-pass', 'forge-spire'],
    lore: 'Não é metáfora. O aço grita. Cada lâmina lembra o nome do dono que ela assou.',
    goldReward: 290,
    heroIds: ['blazborn'],
    dropsLoot: false,
  }),

  /* =========================== STAGE 3 =========================== */
  r({
    id: 'hex-orchard',
    name: 'POMAR DA MALDIÇÃO',
    subtitle: 'Frutas que mordem de volta',
    stage: 3,
    biome: 'verdant',
    x: 14,
    y: 50,
    links: ['midgrove', 'wraith-fen', 'plague-pulpit'],
    lore: 'Toda macieira aqui foi rezada por um padre diferente. As maçãs falam várias línguas mortas.',
    goldReward: 310,
    heroIds: ['vexanna'],
    dropsLoot: false,
  }),
  r({
    id: 'wraith-fen',
    name: 'BREJO DOS ESPECTROS',
    subtitle: 'Onde os vivos pisam fora de hora',
    stage: 3,
    biome: 'moor',
    x: 4,
    y: 48,
    links: ['tundra-gate', 'glass-tundra'],
    // First tier-2 encounter: Bone Orchard map + Husk-King miniboss with
    // thorns. Forces the player to stop face-tanking with melee.
    mapId: 'bone-orchard',
    eliteHeroes: [{ id: 'mb-husk-king', kind: 'miniboss', passiveId: 'thorns' }],
    lore: 'Pisa devagar. A névoa tem horário comercial — e fora dele, ela cobra.',
    goldReward: 320,
    heroIds: ['mb-husk-king', 'vexanna'],
    dropsLoot: true,
  }),
  /* The eight regions below were re-inserted after another bad autofix
     pass collapsed them. Their `links` neighbors still point here, so we
     must restore them. We pin biomes to keep variety: 1 abyss, 1 abyss,
     2 iron, 1 iron, 1 tundra, 2 verdant. */
  r({
    id: 'tideglass',
    name: 'VIDRO DA MARÉ',
    subtitle: 'Onde o mar para de ondular e olha de volta',
    stage: 3,
    biome: 'abyss',
    x: 32,
    y: 78,
    links: ['salt-cloister', 'drowned-warden', 'crab-tide'],
    lore: 'A maré congelou em vidro afiado. Quem cruza descalço deixa parte de si na superfície.',
    goldReward: 330,
    heroIds: ['tyrella'],
    dropsLoot: false,
  }),
  r({
    id: 'crab-tide',
    name: 'MARÉ DE CARANGUEJO',
    subtitle: 'Multidão de carapaças subindo a praia',
    stage: 3,
    biome: 'abyss',
    x: 44,
    y: 82,
    links: ['drowned-warden', 'tideglass', 'sea-lord'],
    lore: 'Não andam pra trás como você imaginava. Andam direto. Pra você.',
    goldReward: 340,
    heroIds: ['daggor'],
    dropsLoot: true,
  }),
  r({
    id: 'ironreach',
    name: 'BRAÇO DE FERRO',
    subtitle: 'Estrada principal do reino, hoje em ruína',
    stage: 3,
    biome: 'iron',
    x: 58,
    y: 70,
    links: ['bog-cathedral', 'sermon-fork', 'pilgrim-pass'],
    lore: 'A pavimentação é todo escudo de soldado tombado em batalha antiga. Pisa devagar, eles ainda escutam.',
    goldReward: 350,
    heroIds: ['kevin'],
    dropsLoot: false,
  }),
  r({
    id: 'pilgrim-pass',
    name: 'PASSO DOS PEREGRINOS',
    subtitle: 'Onde a fé já cansou de andar',
    stage: 3,
    biome: 'iron',
    x: 66,
    y: 74,
    links: ['ironreach', 'sermon-fork', 'flesh-foundry', 'forge-spire'],
    mapId: 'the-gauntlet',
    lore: 'Os peregrinos rezam em fila indiana. Caem em fila indiana. Vão pro mesmo céu, do mesmo jeito.',
    goldReward: 370,
    heroIds: ['gregorius'],
    dropsLoot: true,
  }),
  r({
    id: 'forge-spire',
    name: 'AGULHA DA FORJA',
    subtitle: 'Chaminé que respira gente',
    stage: 3,
    biome: 'iron',
    x: 84,
    y: 70,
    links: ['flesh-foundry', 'pilgrim-pass'],
    lore: 'O turno da noite forja armas. O turno do dia forja heróis. O turno fantasma forja ambos no mesmo tijolo.',
    goldReward: 360,
    heroIds: ['blazborn'],
    dropsLoot: true,
  }),
  /* =========================== STAGE 4 (transition) =========================== */
  r({
    id: 'tundra-gate',
    name: 'PORTA DA TUNDRA',
    subtitle: 'Onde a respiração vira giz',
    stage: 4,
    biome: 'tundra',
    x: 6,
    y: 38,
    links: ['wraith-fen', 'glass-tundra'],
    mapId: 'frozen-confessional',
    lore: 'Tem placa avisando do frio. Os heróis não sabem ler — vai com cuidado.',
    goldReward: 410,
    heroIds: ['baldrik'],
    dropsLoot: false,
  }),
  r({
    id: 'midgrove',
    name: 'BOSQUE-DO-MEIO',
    subtitle: 'Floresta que esquece os caminhos por vingança',
    stage: 4,
    biome: 'verdant',
    x: 16,
    y: 44,
    links: ['hex-orchard', 'thorn-arena', 'sap-altar'],
    mapId: 'buried-archive',
    lore: 'Entrou três vezes. Saiu três vezes. Esqueceu duas das três. Os heróis chamam isso de "exploração".',
    goldReward: 420,
    heroIds: ['vexanna', 'gandolfini'],
    dropsLoot: true,
  }),
  r({
    id: 'thorn-arena',
    name: 'ARENA DOS ESPINHOS',
    subtitle: 'Coliseu vegetal — público de cipó',
    stage: 4,
    biome: 'verdant',
    x: 26,
    y: 38,
    links: ['midgrove', 'cracked-prophecy'],
    mapId: 'convoy-ambush',
    lore: 'A torcida é de cipó. A arquibancada é de espinho. Quando você morre, eles aplaudem mordendo.',
    goldReward: 440,
    heroIds: ['daggor', 'tyrella'],
    dropsLoot: true,
  }),
  r({
    id: 'ashfen',
    name: 'COSTA DA CINZA',
    subtitle: 'Praia negra onde encalham heróis',
    stage: 4,
    biome: 'ash',
    x: 58,
    y: 60,
    links: ['cinder-grove', 'sun-pyre'],
    lore: 'Daggor faz lives de surf. Gandolfini estuda pra prova. Sangue na areia. Engajamento alto.',
    goldReward: 450,
    heroIds: ['daggor', 'gandolfini'],
    dropsLoot: true,
  }),
  r({
    id: 'cinder-grove',
    name: 'BOSQUE DAS BRASAS',
    subtitle: 'Floresta que arde pra dentro',
    stage: 4,
    biome: 'ash',
    x: 64,
    y: 52,
    links: ['sun-pyre', 'gallows-square'],
    // v9 — Hold-out under firestorm. The fire tiles in `ash` biome
    // make this objectively harder than `salt-cloister` — three rounds
    // is enough; the burning floor does the work for you if you stall.
    objective: { kind: 'survive', rounds: 3 },
    lore: 'As árvores morreram em pé há dois séculos. Não caíram. Esperam.',
    goldReward: 430,
    heroIds: ['blazborn'],
    dropsLoot: false,
  }),
  r({
    id: 'umbra-canal',
    name: 'CANAL DA UMBRA',
    subtitle: 'Veia escura sob a capital',
    stage: 4,
    biome: 'abyss',
    x: 42,
    y: 70,
    links: ['wretch-quay', 'ashfen'],
    lore: 'A água é um pacto líquido. Quem engole, devolve em juros — pulando da própria garganta.',
    goldReward: 440,
    heroIds: ['gregorius'],
    dropsLoot: false,
  }),

  /* =========================== STAGE 5 =========================== */
  r({
    id: 'frostmarch',
    name: 'MARCHA DE GELO',
    subtitle: 'Coluna que não chega',
    stage: 5,
    biome: 'tundra',
    x: 4,
    y: 22,
    links: ['glass-tundra', 'mind-archive'],
    lore: 'Era um exército. Agora é uma fila. Cada soldado um grau a menos.',
    goldReward: 470,
    heroIds: ['baldrik'],
    dropsLoot: false,
  }),
  r({
    id: 'pale-cathedral',
    name: 'CATEDRAL PÁLIDA',
    subtitle: 'Onde até os santos batem queixo',
    stage: 5,
    biome: 'tundra',
    x: 14,
    y: 18,
    links: ['glass-tundra', 'hollow-belfry'],
    lore: 'Vitrais de gelo. Os relicários ainda apitam — alguém dentro respira.',
    goldReward: 510,
    heroIds: ['heliarch'],
    dropsLoot: true,
  }),
  r({
    id: 'glass-tundra',
    name: 'TUNDRA DE VIDRO',
    subtitle: 'Lago onde caminham mortos coletivos',
    stage: 5,
    biome: 'tundra',
    x: 24,
    y: 26,
    links: ['mind-archive', 'pale-cathedral'],
    lore: 'A superfície aguenta um homem. Aguenta dois. Não aguenta uma profissão de fé.',
    goldReward: 490,
    heroIds: ['profecia'],
    dropsLoot: false,
  }),
  r({
    id: 'kingreach',
    name: 'ALCANCE DO REI',
    subtitle: 'Capital sob impostos sob impostos',
    stage: 5,
    biome: 'iron',
    x: 70,
    y: 38,
    links: ['gilded-rookery', 'royal-archives'],
    lore: 'Baldrik patenteou a lei. Midas auditou seu CNPJ. Gregórius está mandando áudio.',
    goldReward: 580,
    heroIds: ['baldrik', 'gregorius', 'midas'],
    dropsLoot: true,
  }),
  r({
    id: 'sun-pyre',
    name: 'PIRA SOLAR',
    subtitle: 'Altar que confunde luz com perdão',
    stage: 5,
    biome: 'ash',
    x: 74,
    y: 50,
    links: ['gallows-square', 'ember-isthmus', 'volcan-temple'],
    lore: 'Sacerdotes-solar acreditam que queimar é abençoar. Vão te abençoar muito. Por muito tempo.',
    goldReward: 560,
    heroIds: ['heliarch'],
    dropsLoot: false,
  }),
  r({
    id: 'wretch-quay',
    name: 'CAIS DOS DESGRAÇADOS',
    subtitle: 'Atracadouro que não solta',
    stage: 5,
    biome: 'abyss',
    x: 46,
    y: 78,
    links: ['sea-lord', 'umbra-canal'],
    lore: 'Cada navio aqui chegou afundado. Atracam mesmo assim — a doca cobra estadia além da morte.',
    goldReward: 540,
    heroIds: ['kevin'],
    dropsLoot: true,
  }),

  /* =========================== STAGE 6 =========================== */
  r({
    id: 'gilded-rookery',
    name: 'TORRE DOURADA',
    subtitle: 'Bibliotecários auditando o céu',
    stage: 6,
    biome: 'iron',
    x: 78,
    y: 34,
    links: ['gallows-square', 'sky-stable'],
    // Thunderhead-ridge — three-tier highground; Twin Saints revive each
    // other so you must spike both within the same round.
    mapId: 'thunderhead-ridge',
    eliteHeroes: [{ id: 'mb-twin-saints', kind: 'miniboss', passiveId: 'revive' }],
    // v9 — Heist mission. Midas is the auditor; the Twin Saints are
    // his bodyguards. Killing only Midas ends the mission — the Saints
    // walk away. Rewards focus on outplaying the revive-pair instead
    // of brute-forcing it.
    objective: { kind: 'assassinate', targetHeroId: 'midas' },
    lore: 'Cada andar é um cofre, cada cofre é uma alma penhorada. Os juros estão atrasados.',
    goldReward: 600,
    heroIds: ['mb-twin-saints', 'midas'],
    dropsLoot: false,
  }),
  r({
    id: 'royal-archives',
    name: 'ARQUIVO REAL',
    subtitle: 'Pergaminhos que se editam sozinhos',
    stage: 6,
    biome: 'iron',
    x: 64,
    y: 30,
    links: ['sky-stable', 'choir-pit'],
    // Buried-archive bookshelf killbox + Debt Collector miniboss with
    // time-stop passive. Hits twice when you've already spent your turn.
    mapId: 'buried-archive',
    eliteHeroes: [
      { id: 'mb-debt-collector', kind: 'miniboss', passiveId: 'time-stop' },
    ],
    lore: 'Os escribas ainda escrevem você como vilão. Eles não erram — eles obedecem.',
    goldReward: 590,
    heroIds: ['mb-debt-collector', 'gregorius'],
    dropsLoot: false,
  }),
  r({
    id: 'gallows-square',
    name: 'PRAÇA DO PATÍBULO',
    subtitle: 'Mercado onde se compra silêncio',
    stage: 6,
    biome: 'iron',
    x: 82,
    y: 44,
    links: ['dune-singers', 'ember-isthmus'],
    lore: 'O carrasco vende relíquias. Cada uma com uma confissão impressa em sangue seco.',
    goldReward: 620,
    heroIds: ['baldrik'],
    dropsLoot: true,
  }),
  r({
    id: 'sea-lord',
    name: 'TRONO DAS PROFUNDAS',
    subtitle: 'Sala onde a maré bate em três vozes',
    stage: 6,
    biome: 'abyss',
    x: 52,
    y: 86,
    links: ['ember-isthmus', 'wretch-quay', 'tide-throne'],
    // Kraken-rise reused — shipwreck arena fits "três vozes" choir + boss.
    mapId: 'kraken-rise',
    lore: 'O Senhor do Mar perdeu o trono pra um tubarão letrado. Voltou do exílio. Trouxe currículo.',
    goldReward: 670,
    heroIds: ['mb-temple-twins', 'heliarch', 'profecia'],
    eliteHeroes: [{ id: 'mb-temple-twins', kind: 'miniboss', passiveId: 'lifesteal' }],
    dropsLoot: true,
  }),
  r({
    id: 'mind-archive',
    name: 'ARQUIVO DE MENTES',
    subtitle: 'Sala que guarda só o que dói lembrar',
    stage: 6,
    biome: 'tundra',
    x: 24,
    y: 12,
    links: ['inverse-monastery', 'hollow-belfry'],
    lore: 'Tem uma estante reservada pra você. Os outros Underlords pediram pra ler primeiro.',
    goldReward: 640,
    heroIds: ['gandolfini', 'midas'],
    dropsLoot: false,
  }),

  /* =========================== STAGE 7 =========================== */
  r({
    id: 'dune-singers',
    name: 'CANTADORAS DAS DUNAS',
    subtitle: 'Vento que decora teus pesadelos',
    stage: 7,
    biome: 'dunes',
    x: 88,
    y: 56,
    links: ['glass-mirage', 'salt-tomb'],
    lore: 'Não são vozes. É a areia. Ela aprende rápido. Se você dormir aqui, ela vai chamar tua mãe.',
    goldReward: 680,
    heroIds: ['daggor'],
    dropsLoot: false,
  }),
  r({
    id: 'glass-mirage',
    name: 'MIRAGEM DE VIDRO',
    subtitle: 'Cidade que desaparece quando vista',
    stage: 7,
    biome: 'dunes',
    x: 94,
    y: 48,
    links: ['salt-tomb', 'wyrm-shelf', 'glasspriest'],
    // Sandstorm-spire reused with a different cast — solar mirage variant.
    mapId: 'sandstorm-spire',
    lore: 'Os habitantes te cumprimentam. Não estão lá. Os cumprimentos, sim.',
    goldReward: 700,
    heroIds: ['mb-dawn-herald', 'vexanna'],
    eliteHeroes: [{ id: 'mb-dawn-herald', kind: 'miniboss', passiveId: 'phase' }],
    dropsLoot: true,
  }),
  r({
    id: 'salt-tomb',
    name: 'TUMBA DE SAL',
    subtitle: 'Pirâmide que cresce de dentro',
    stage: 7,
    biome: 'dunes',
    x: 92,
    y: 64,
    links: ['crown-causeway', 'wyrm-shelf'],
    lore: 'Os reis do sal nunca foram coroados — só desidratados. Eles ainda governam, em escala mineral.',
    goldReward: 720,
    heroIds: ['heliarch'],
    dropsLoot: false,
  }),
  r({
    id: 'sky-stable',
    name: 'ESTÁBULO DOS GRIFOS',
    subtitle: 'Onde os heróis param pra carregar EGO',
    stage: 7,
    biome: 'verdant',
    x: 70,
    y: 22,
    links: ['hollow-belfry', 'choir-pit'],
    lore: 'Cavalheiros enchem o tanque. Os grifos cospem. O frentista é um santo desempregado.',
    goldReward: 690,
    heroIds: ['daggor'],
    dropsLoot: false,
  }),
  r({
    id: 'ember-isthmus',
    name: 'ISTMO DE BRASA',
    subtitle: 'Faixa fina de terra entre dois infernos',
    stage: 7,
    biome: 'ash',
    x: 50,
    y: 58,
    links: ['wyrm-shelf', 'inverse-monastery'],
    lore: 'Dois mares de fogo. Um caminho. Quem para, vira combustível pros dois lados.',
    goldReward: 730,
    heroIds: ['blazborn', 'vexanna'],
    dropsLoot: false,
  }),

  /* =========================== STAGE 8 =========================== */
  r({
    // The-gauntlet — narrow vertical corridor matches the prison-chimney
    // theme. Carcereiro at the top, you climb up under fire.
    mapId: 'the-gauntlet',
    eliteHeroes: [{ id: 'mb-warden', kind: 'miniboss', passiveId: 'enrage' }],
    id: 'hollow-belfry',
    name: 'CAMPANÁRIO OCO',
    subtitle: 'Sino sem badalo, badalo sem sino',
    stage: 8,
    biome: 'iron',
    x: 78,
    y: 18,
    links: ['choir-pit', 'inverse-monastery'],
    lore: 'Quando bate, todo mundo dentro de mil léguas pensa que é a vez deles. Geralmente não é.',
    goldReward: 780,
    heroIds: ['gregorius', 'tyrella'],
    dropsLoot: true,
  }),
  r({
    id: 'crown-causeway',
    name: 'CAUSEWAY DA COROA',
    subtitle: 'Ponte que oscila entre dois mundos',
    stage: 8,
    biome: 'crown',
    x: 86,
    y: 26,
    links: ['inverse-monastery', 'eyeless-bridge'],
    lore: 'Cada pedra é uma promessa quebrada. Você vai pisar em todas — e elas te conhecem pelo nome.',
    goldReward: 800,
    heroIds: ['baldrik', 'heliarch'],
    dropsLoot: false,
  }),
  r({
    id: 'wyrm-shelf',
    name: 'PLATAFORMA DO WYRM',
    subtitle: 'Cornija com cheiro de réptil bíblico',
    stage: 8,
    biome: 'crown',
    x: 90,
    y: 36,
    links: ['eyeless-bridge', 'usurper-hall'],
    // Kraken-rise — boss arena with massive shipwreck. Mirror Knight is
    // a thorns miniboss, punishing burst-damage strats.
    mapId: 'kraken-rise',
    eliteHeroes: [{ id: 'mb-mirror-knight', kind: 'miniboss', passiveId: 'thorns' }],
    // v9 — Late-game assassination. Mirror Knight is the marquee — kill
    // him and the wyrm wakes up; Profecia is incidental. Punishes
    // burst comps that try to focus the squishy first.
    objective: { kind: 'assassinate', targetHeroId: 'mb-mirror-knight' },
    lore: 'O wyrm dormia aqui. Ainda dorme. Ronca em latim eclesiástico.',
    goldReward: 830,
    heroIds: ['mb-mirror-knight', 'profecia'],
    dropsLoot: false,
  }),
  r({
    id: 'choir-pit',
    name: 'POÇO DO CORO',
    subtitle: 'Doze vozes, zero descanso',
    stage: 8,
    biome: 'verdant',
    x: 36,
    y: 24,
    links: ['cracked-prophecy', 'inverse-monastery'],
    // Buried-archive (chess shelves) reused for a verdant tomb-library look.
    mapId: 'buried-archive',
    eliteHeroes: [{ id: 'mb-spore-priest', kind: 'miniboss', passiveId: 'summon' }],
    lore: 'Cantam doze horas, descansam zero. Quem ouve até o fim concorda em qualquer coisa.',
    goldReward: 850,
    heroIds: ['vexanna', 'tyrella'],
    dropsLoot: true,
  }),
  r({
    id: 'inverse-monastery',
    name: 'MOSTEIRO INVERSO',
    subtitle: 'Pegando a oração ao avesso',
    stage: 8,
    biome: 'crown',
    x: 76,
    y: 8,
    links: ['cracked-prophecy', 'usurper-hall'],
    lore: 'Os monges rezam pelo fim. O fim agradece com cartão escrito.',
    goldReward: 870,
    heroIds: ['gregorius', 'profecia'],
    dropsLoot: false,
  }),

  /* =========================== STAGE 9 =========================== */
  r({
    id: 'cracked-prophecy',
    name: 'PROFECIA RACHADA',
    subtitle: 'Pergaminho dobrado por dentro',
    stage: 9,
    biome: 'tundra',
    x: 50,
    y: 8,
    links: ['usurper-hall', 'eyeless-bridge'],
    lore: 'A profecia se contradiz duas vezes por parágrafo. Quem decifra, escreve a próxima.',
    goldReward: 900,
    heroIds: ['profecia'],
    dropsLoot: false,
  }),
  r({
    id: 'eyeless-bridge',
    name: 'PONTE SEM OLHOS',
    subtitle: 'Atravessa de fé. Ou não atravessa.',
    stage: 9,
    biome: 'crown',
    x: 84,
    y: 20,
    links: ['usurper-hall', 'sunkencrown'],
    lore: 'A ponte não enxerga você. Você precisa enxergar a ponte. É o teste.',
    goldReward: 940,
    heroIds: ['heliarch', 'baldrik'],
    dropsLoot: true,
  }),

  /* =========================== STAGE 10 =========================== */
  // Stage 10 mid-boss arena. Profecia is the boss (enrage at 50% HP),
  // Baldrik is a thorns miniboss — punishes the player for hitting him
  // melee, forcing ranged-archetype thinking before the final fight.
  r({
    id: 'usurper-hall',
    name: 'SALÃO DOS USURPADORES',
    subtitle: 'Sete tronos vazios que ainda te julgam',
    stage: 10,
    biome: 'crown',
    x: 78,
    y: 14,
    links: ['sunkencrown'],
    lore: 'Cada Underlord anterior deixou aqui sua coroa partida. Você vai precisar de algum lugar pra sentar.',
    goldReward: 1100,
    heroIds: ['profecia', 'baldrik'],
    eliteHeroes: [
      { id: 'profecia', kind: 'boss', passiveId: 'enrage' },
      { id: 'baldrik', kind: 'miniboss', passiveId: 'thorns' },
    ],
    dropsLoot: true,
  }),

  /* =========================== STAGE 14 (BOSS) =========================== */
  // Final encounter — DOUBLE boss. Profecia revives once at 50% HP and
  // Heliarch broadcasts a +25% damage aura to nearby allies. The combo is
  // designed to feel unfair on first attempt: the player must pick which
  // boss to bury first, knowing one of them will rescue itself.
  r({
    id: 'sunkencrown',
    name: 'A COROA SUBMERSA',
    subtitle: 'Topo da torre, último degrau',
    stage: 14,
    biome: 'crown',
    x: 90,
    y: 6,
    // After winning here the campaign continues into the Ciclo Eterno
    // (stages 15-20). Six post-game boss arenas, one per surviving boss
    // archetype, opening fan-out from the throne.
    links: ['eternity-foyer'],
    lore: 'A Profecia em Pessoa te aguarda. Heliarch também. Nem dão bom dia.',
    goldReward: 2400,
    heroIds: ['profecia', 'heliarch'],
    eliteHeroes: [
      { id: 'profecia', kind: 'boss', passiveId: 'revive' },
      { id: 'heliarch', kind: 'boss', passiveId: 'aura-rage' },
    ],
    dropsLoot: true,
  }),

  /* ============== AÇOS PARALELOS — desbloqueados via cinder-grove,
                    forge-spire, gallows-square. Aprofundam o tema iron. ============== */
  r({
    id: 'mint-vault',
    name: 'CONFIARIA DO COFRE',
    subtitle: 'Casa da Moeda em descanso eterno',
    stage: 5,
    biome: 'iron',
    x: 86,
    y: 62,
    links: ['gallows-square', 'forge-vein', 'caravan-gallows'],
    lore: 'Os tesoureiros foram embora ricos — e mortos. As moedas continuam contando, sozinhas.',
    goldReward: 520,
    heroIds: ['midas'],
    dropsLoot: false,
  }),
  r({
    id: 'forge-vein',
    name: 'VEIA DA FORJA',
    subtitle: 'Galeria onde o ferro respira',
    stage: 6,
    biome: 'iron',
    x: 90,
    y: 56,
    links: ['gallows-square', 'wyrm-shelf'],
    lore: 'A pedreira é viva. Você martela; ela martela de volta. A última nota desafina pro teu lado.',
    goldReward: 660,
    heroIds: ['blazborn'],
    dropsLoot: true,
  }),

  /* ============== EXTENSÃO MOOR — desbloqueada via lichmoor, rotwell ============== */
  r({
    id: 'reedfen-altar',
    name: 'ALTAR DOS JUNCOS',
    subtitle: 'Pântano que recebe oferendas verticais',
    stage: 2,
    biome: 'moor',
    x: 10,
    y: 70,
    links: ['hex-orchard', 'rotwell'],
    lore: 'Eles plantam estacas com doutrinas. Crescem como junco — e cortam como junco.',
    goldReward: 245,
    heroIds: ['bryan'],
    dropsLoot: false,
  }),
  r({
    id: 'plague-pulpit',
    name: 'PÚLPITO DA PESTE',
    subtitle: 'Sermão por inalação',
    stage: 4,
    biome: 'moor',
    x: 18,
    y: 38,
    links: ['glass-tundra', 'hex-orchard'],
    lore: 'O sacerdote fala baixo. Você inspira fundo. A doutrina entra. Não sai.',
    goldReward: 405,
    heroIds: ['gandolfini'],
    dropsLoot: false,
  }),

  /* ============== EXTENSÃO ABYSS — extras dos cais e marés ============== */
  r({
    id: 'kelpwall',
    name: 'MURO DE KELP',
    subtitle: 'Algas que cantam o nome dos afogados',
    stage: 4,
    biome: 'abyss',
    x: 32,
    y: 80,
    links: ['umbra-canal', 'crab-tide'],
    lore: 'Cada folha conhece um nome. Quando chegam ao seu, todas calam. É um silêncio que pesa.',
    goldReward: 415,
    heroIds: ['heliarch'],
    dropsLoot: false,
  }),
  // Mid-game lifesteal miniboss — Kevin keeps healing himself off your
  // squad. Forces the player to focus-fire instead of spreading damage.
  r({
    id: 'tide-throne',
    name: 'TRONO DA MARÉ',
    subtitle: 'Sentar é se afogar lentamente',
    stage: 7,
    biome: 'abyss',
    x: 56,
    y: 80,
    links: ['sea-lord', 'ember-isthmus'],
    lore: 'O assento se enche a cada lua. Quem reina respira a metade do tempo. Os outros, nenhum.',
    goldReward: 705,
    heroIds: ['kevin'],
    eliteHeroes: [{ id: 'kevin', kind: 'miniboss', passiveId: 'lifesteal' }],
    dropsLoot: true,
  }),

  /* ============== EXTENSÃO TUNDRA ============== */
  r({
    id: 'pyre-of-ice',
    name: 'PIRA DE GELO',
    subtitle: 'Fogo que congela em vez de queimar',
    stage: 5,
    biome: 'tundra',
    x: 18,
    y: 14,
    links: ['mind-archive', 'pale-cathedral', 'frozen-confessional'],
    lore: 'A chama é azul. Cada lasca de calor te tira um. Quem se aquece, esquece.',
    goldReward: 500,
    heroIds: ['gandolfini'],
    dropsLoot: false,
  }),
  r({
    id: 'frozen-confessional',
    name: 'CONFESSIONÁRIO CONGELADO',
    subtitle: 'Onde a culpa cristaliza',
    stage: 7,
    biome: 'tundra',
    x: 30,
    y: 6,
    links: ['cracked-prophecy', 'mind-archive'],
    lore: 'Pequena cabine. Te ouve. Te julga. Te empacota. Te empilha junto.',
    goldReward: 715,
    heroIds: ['tyrella'],
    dropsLoot: true,
  }),

  /* ============== EXTENSÃO DUNES ============== */
  r({
    id: 'glasspriest',
    name: 'PADRE DE VIDRO',
    subtitle: 'Reza que reflete antes de sair da boca',
    stage: 8,
    biome: 'dunes',
    x: 96,
    y: 56,
    links: ['wyrm-shelf', 'eyeless-bridge'],
    lore: 'Quando ele te abençoa, você se vê amaldiçoado por dois segundos antes. Útil.',
    goldReward: 820,
    heroIds: ['heliarch'],
    dropsLoot: false,
  }),
  r({
    id: 'caravan-gallows',
    name: 'CARAVANA DA FORCA',
    subtitle: 'Comerciantes que vendem condenação',
    stage: 6,
    biome: 'dunes',
    x: 92,
    y: 58,
    links: ['salt-tomb', 'glass-mirage'],
    lore: 'O comércio é simples: tu compra, eles enforcam. Tu vende, eles enforcam. Tu olha, eles enforcam.',
    goldReward: 645,
    heroIds: ['baldrik'],
    dropsLoot: false,
  }),

  /* ============== EXTENSÃO VERDANT — bosque profano ============== */
  r({
    id: 'rootlich',
    name: 'LICHE-RAIZ',
    subtitle: 'Raiz que mastiga doutrina',
    stage: 3,
    biome: 'verdant',
    x: 28,
    y: 36,
    links: ['midgrove', 'plague-pulpit'],
    lore: 'A árvore-mãe morreu há séculos. Ainda lembra de cada peregrino que dormiu sob ela. Quer cumprimentar.',
    goldReward: 350,
    heroIds: ['vexanna'],
    dropsLoot: false,
  }),
  r({
    id: 'sap-altar',
    name: 'ALTAR DA SEIVA',
    subtitle: 'Onde se assina contrato com floresta',
    stage: 5,
    biome: 'verdant',
    x: 42,
    y: 28,
    links: ['choir-pit', 'thorn-arena'],
    lore: 'Você assina com o dedo. A floresta te lê. Devolve um contrato em látex e nomes mortos.',
    goldReward: 530,
    heroIds: ['vexanna'],
    dropsLoot: true,
  }),

  /* ============== EXTENSÃO ASH — lua escura, vulcanal ============== */
  r({
    id: 'pyre-quay',
    name: 'CAIS DE PIRAS',
    subtitle: 'Atracadouro que arde por contrato',
    stage: 4,
    biome: 'ash',
    x: 70,
    y: 70,
    links: ['ember-isthmus', 'cinder-grove'],
    lore: 'Os capitães acendem o navio antes de partir. É tradição. É contrato. É castigo.',
    goldReward: 425,
    heroIds: ['blazborn'],
    dropsLoot: false,
  }),
  // Heliarch boss with summon (calls 2 minions at 50% HP) + Blazborn
  // miniboss with thorns. The summon punishes a slow grind; thorns
  // punishes burst — players have to balance their damage curve.
  r({
    id: 'volcan-temple',
    name: 'TEMPLO DO VULCAL',
    subtitle: 'Onde a montanha discute teologia',
    stage: 6,
    biome: 'ash',
    x: 68,
    y: 46,
    links: ['gallows-square', 'sun-pyre'],
    lore: 'A erupção é argumentativa. Cada lasca de basalto é um postulado. Os fiéis morrem citados.',
    goldReward: 615,
    heroIds: ['heliarch', 'blazborn'],
    eliteHeroes: [
      { id: 'heliarch', kind: 'boss', passiveId: 'summon' },
      { id: 'blazborn', kind: 'miniboss', passiveId: 'thorns' },
    ],
    dropsLoot: true,
  }),

  /* ============================================================================
   * CICLO ETERNO — endgame stages 15-20.
   *
   * After the player beats `sunkencrown`, the throne shatters into the
   * Ciclo Eterno: six bespoke boss arenas, each tuned around ONE of the
   * BOSSES (lib/elementum-flavor.ts). Each region has:
   *   - A unique signature mapId that has never been seen before.
   *   - The boss as the marquee enemy with a stat overlay + named passive.
   *   - 4-5 entourage minions (the boss's catalog `entourage` field is
   *     authoritative — they spawn alongside the boss as hero-minions).
   *   - High goldReward + dropsLoot so post-game is materially worthwhile.
   *
   * Each arena links forward to the next so the loop is sequential. The
   * final boss `boss-eternity` has no outgoing links — beating it is the
   * 100% completion of the campaign.
   * ============================================================================ */

  r({
    id: 'eternity-foyer',
    name: 'O VESTÍBULO DO CICLO',
    subtitle: 'Antessala do tempo que não acaba',
    stage: 15,
    biome: 'crown',
    x: 92,
    y: 14,
    links: ['iron-conclave'],
    mapId: 'coronation-hall',
    lore: 'Você matou os tronos. Eles se reorganizaram em fila. Agora cada um quer um turno.',
    goldReward: 2700,
    heroIds: ['boss-iron-pope'],
    eliteHeroes: [
      { id: 'boss-iron-pope', kind: 'boss', passiveId: 'aura-rage' },
    ],
    dropsLoot: true,
  }),

  r({
    id: 'iron-conclave',
    name: 'CONCLAVE-FERRO',
    subtitle: 'O Papa-Ferro decide sua excomunhão',
    stage: 16,
    biome: 'iron',
    x: 86,
    y: 22,
    links: ['drowning-court'],
    mapId: 'fallen-cathedral',
    lore: 'Os cardeais já votaram. Você foi a maioria. (Maioria contra você.)',
    goldReward: 3000,
    heroIds: ['boss-tide-empress'],
    eliteHeroes: [
      { id: 'boss-tide-empress', kind: 'boss', passiveId: 'lifesteal' },
    ],
    dropsLoot: true,
  }),

  r({
    id: 'drowning-court',
    name: 'CORTE AFOGADA',
    subtitle: 'A Imperatriz das Marés convoca audiência',
    stage: 17,
    biome: 'abyss',
    x: 76,
    y: 30,
    links: ['fork-of-time'],
    mapId: 'kraken-rise',
    lore: 'O processo é rápido. A pena é eterna. A imperatriz não recebe recursos — só corpos.',
    goldReward: 3300,
    heroIds: ['boss-time-warden'],
    eliteHeroes: [
      { id: 'boss-time-warden', kind: 'boss', passiveId: 'time-stop' },
    ],
    dropsLoot: true,
  }),

  r({
    id: 'fork-of-time',
    name: 'FURCAÇÃO DO TEMPO',
    subtitle: 'Onde o Guardião abre dois agora',
    stage: 18,
    biome: 'crown',
    x: 64,
    y: 36,
    links: ['hero-superposition'],
    mapId: 'hall-of-mirrors',
    lore: 'Ele já viu sua morte. Você só precisa concordar com o roteiro dele uma vez.',
    goldReward: 3600,
    heroIds: ['boss-final-hero'],
    eliteHeroes: [
      { id: 'boss-final-hero', kind: 'boss', passiveId: 'enrage' },
    ],
    dropsLoot: true,
  }),

  r({
    id: 'hero-superposition',
    name: 'SUPERPOSIÇÃO DO HERÓI',
    subtitle: 'Todos os heróis num só corpo, simultâneos',
    stage: 19,
    biome: 'verdant',
    x: 50,
    y: 42,
    links: ['authors-margin'],
    mapId: 'broken-coliseum',
    lore: 'Bryan, Tyrella, Daggor, Padre Gregórius — todos lá dentro. Todos lembram. Todos cobram.',
    goldReward: 4000,
    heroIds: ['boss-author'],
    eliteHeroes: [
      { id: 'boss-author', kind: 'boss', passiveId: 'phase' },
    ],
    dropsLoot: true,
  }),

  r({
    id: 'authors-margin',
    name: 'A MARGEM DO AUTOR',
    subtitle: 'O Autor te lê em primeira pessoa',
    stage: 19,
    biome: 'iron',
    x: 36,
    y: 48,
    links: ['eternity-loop'],
    mapId: 'drowned-library',
    lore: 'Já está no rascunho. Você é o terceiro ato. O quarto não foi escrito. Pode ser seu.',
    goldReward: 4500,
    heroIds: ['boss-author'],
    eliteHeroes: [
      { id: 'boss-author', kind: 'boss', passiveId: 'phase' },
    ],
    dropsLoot: true,
  }),

  r({
    id: 'eternity-loop',
    name: 'O CICLO ETERNO',
    subtitle: 'A Eternidade em pessoa, último encontro',
    stage: 20,
    biome: 'crown',
    x: 22,
    y: 54,
    // v11 — beating the Ciclo Eterno no longer ends the campaign. The
    // shattered loop spills upward into A ASCENSÃO: the eight industrial
    // ascension minibosses, then the descent into O VAZIO and the six
    // final bosses. `rust-keep` is the first rung of the new act.
    links: ['rust-keep'],
    mapId: 'throne-room',
    lore: 'Sem rosto, só padrão. Sem voz, só ressonância. Mata você no presente, no passado e no futuro — simultâneos.',
    goldReward: 6000,
    heroIds: ['boss-eternity'],
    eliteHeroes: [
      { id: 'boss-eternity', kind: 'boss', passiveId: 'revive' },
    ],
    dropsLoot: true,
  }),

  /* ============================================================================
   * v11 — A ASCENSÃO / O VAZIO
   *
   * O Ciclo Eterno não era o fim — era o último degrau ANTES do fim. Quem
   * sobrevive à Eternidade descobre que ela só estava segurando a porta.
   *
   * Esta act tem duas metades:
   *
   *   1) A ASCENSÃO (estágios 12-18) — seis mini-chefões industriais
   *      espalhados pelos biomas antigos (iron, dunes, moor, tundra, crown),
   *      cada um um vício humano vestido de monstro. Cadeia linear com
   *      objetivos variados (overwhelm/survive) pra quebrar o grind. Todos
   *      `dropsLoot:true`. Reconverge no portão do Vazio.
   *
   *   2) O VAZIO (estágios 24-34, biome:'void') — a descida final pelo fundo
   *      da Subtorre até a página em branco do Autor. Sequência quase linear
   *      e escalonante (estágios altos = loot mítico, que desbloqueia no 18+).
   *      Termina nos SEIS chefões finais, em ordem canônica de lore:
   *        Rei Oco → Mãe da Praga → O Não-Escrito → O Eu no Espelho →
   *        O Primeiro Underlord → O LEITOR (chefe final absoluto).
   *      Cada arena de chefe usa o mapId de assinatura do Vazio
   *      (foyer/archive/throne/mirror/press/end) e o passiveId correto.
   *
   * GRAFO: `rust-keep` é puxado pelos links de `eternity-loop` (vide acima).
   * A act inteira é forward e sem dead end — só `void-the-reader` (chefe
   * final) tem `links: []`, fechando 100% da campanha.
   * ============================================================================ */

  /* ----- A ASCENSÃO — seis mini-chefões industriais ----- */

  r({
    id: 'rust-keep',
    name: 'O TORREÃO ENFERRUJADO',
    subtitle: 'Fortaleza que se reconstrói em óxido',
    stage: 12,
    biome: 'iron',
    x: 14,
    y: 48,
    links: ['siphon-choir'],
    // Rust Baron regenerates 12% hpMax every round — an overwhelm clock
    // forces the player to out-DPS the regen instead of chipping forever.
    objective: { kind: 'overwhelm', rounds: 8 },
    lore: 'O Barão Enferrujado não defende um reino — defende a própria ferrugem, que ele considera patrimônio histórico. Cada lasca que você arranca volta a crescer marrom, viçosa, orgulhosa, no compasso de um relógio que ele engoliu há séculos. Bata rápido, vilão: o tétano dele tem mais paciência do que você, e o torreão inteiro range concordando.',
    goldReward: 1300,
    heroIds: ['mb-rust-baron', 'baldrik', 'midas'],
    eliteHeroes: [{ id: 'mb-rust-baron', kind: 'miniboss', passiveId: 'regenerate' }],
    dropsLoot: true,
  }),
  r({
    id: 'siphon-choir',
    name: 'O CORO DA SANGRIA',
    subtitle: 'Regência que cura cantando alto',
    stage: 13,
    biome: 'crown',
    x: 24,
    y: 42,
    links: ['glass-throne'],
    lore: 'A Regente do Coro afina o coral celeste com as duas mãos enquanto cada nota costura de volta os fiéis que você acabou de abrir. Em dó maior, em sol menor, em qualquer tom — a aura dela derrama graça nos vizinhos a cada compasso, e o desgraçado do som não cansa nunca. Você fere um soprano; ela ressuscita dois contraltos. É matemática litúrgica, e a conta nunca fecha a seu favor.',
    goldReward: 1450,
    heroIds: ['mb-choir-mistress', 'heliarch', 'gregorius'],
    eliteHeroes: [{ id: 'mb-choir-mistress', kind: 'miniboss', passiveId: 'siphon-aura' }],
    dropsLoot: true,
  }),
  r({
    id: 'glass-throne',
    name: 'O TRONO DE VIDRO',
    subtitle: 'Déspota opaco que absorve pancada',
    stage: 14,
    biome: 'iron',
    x: 34,
    y: 36,
    links: ['saint-bog'],
    lore: 'O Tirano de Vidro mandou esculpir o próprio corpo em vitral temperado pra parecer eterno, e a piada cruel é que funcionou: parece que estilhaça ao primeiro golpe, mas o desgraçado é grosso, opaco e engole pancada como catedral cara. Você vê direto através dele e mesmo assim não consegue feri-lo direito. Ele te observa morrer com a transparência tediosa de quem já sabia o final.',
    goldReward: 1600,
    heroIds: ['mb-glass-tyrant', 'profecia'],
    eliteHeroes: [{ id: 'mb-glass-tyrant', kind: 'miniboss', passiveId: 'colossal' }],
    dropsLoot: true,
  }),
  r({
    id: 'saint-bog',
    name: 'O BREJO DO SANTO',
    subtitle: 'Eremita que desova ao morrer',
    stage: 15,
    biome: 'moor',
    x: 22,
    y: 54,
    links: ['veil-dune'],
    // Survive: the Bog Saint splits on death into two soggy disciples, so
    // killing him spawns MORE problems. Holding out four rounds teaches the
    // player that brute-forcing the split is a trap.
    objective: { kind: 'survive', rounds: 4 },
    lore: 'O Santo do Brejo se afogou em fé e em água parada e voltou coberto de fungo abençoado, pregando a parábola dos pães em versão mofo. Quando você acha que o matou, ele desova em dois santinhos menores, igualmente úmidos e igualmente convencidos de que cada esporo é um discípulo carnívoro. O brejo é o altar dele; você foi convocado como oferenda, e o sermão entra pela respiração e não sai mais.',
    goldReward: 1750,
    heroIds: ['mb-bog-saint', 'bryan', 'gandolfini'],
    eliteHeroes: [{ id: 'mb-bog-saint', kind: 'miniboss', passiveId: 'split' }],
    dropsLoot: true,
  }),
  r({
    id: 'veil-dune',
    name: 'A DUNA DO VÉU',
    subtitle: 'Conselheiro coberto de areia que escuda',
    stage: 16,
    biome: 'dunes',
    x: 40,
    y: 48,
    links: ['frost-abbey'],
    lore: 'O Vizir das Dunas aconselha um sultão que ninguém nunca viu, porque há séculos é o véu de areia dele quem governa. A cada round a tempestade obediente puxa uma cortina nova de pó que engole seus golpes antes de chegarem na pele perfumada, um escudo que se refaz mais rápido do que sua paciência. Ele não reina, insiste — apenas aconselha. Letalmente. E já sussurrou sua sentença ao ouvido de um trono vazio.',
    goldReward: 1900,
    heroIds: ['mb-dune-vizier', 'daggor'],
    eliteHeroes: [{ id: 'mb-dune-vizier', kind: 'miniboss', passiveId: 'warding' }],
    dropsLoot: true,
  }),
  r({
    id: 'frost-abbey',
    name: 'A ABADIA DO GELO',
    subtitle: 'Monge silencioso que sangra ao toque',
    stage: 18,
    biome: 'tundra',
    x: 30,
    y: 60,
    links: ['void-foyer-region'],
    // Overwhelm under the cold: the Frost Abbot bleeds you with every hit
    // (frostbite). Stalling = death by a thousand cuts, so race the clock.
    objective: { kind: 'overwhelm', rounds: 10 },
    lore: 'O Abade do Gelo fez voto de silêncio, de pobreza e de hipotermia, e cumpre os três com um fervor monástico que dá inveja. Cada toque dele te corta com lâmina de gelo, e o corte não fecha — fica sangrando que nem promessa de monge quebrada, gota a gota, voto de penitência escrito na sua carne. No mosteiro eles jejuam; aqui é você quem esvazia. A paz gélida dele é permanente, e ela tem pressa de chegar à sua.',
    goldReward: 2200,
    heroIds: ['mb-frost-abbot', 'baldrik', 'tyrella'],
    eliteHeroes: [{ id: 'mb-frost-abbot', kind: 'miniboss', passiveId: 'frostbite' }],
    dropsLoot: true,
  }),

  /* ----- O VAZIO — a descida final, biome:'void', loot mítico ----- */

  r({
    id: 'void-foyer-region',
    name: 'O LIMIAR DO VAZIO',
    subtitle: 'Onde o chão da Subtorre simplesmente acaba',
    stage: 24,
    biome: 'void',
    x: 18,
    y: 70,
    links: ['void-descent'],
    mapId: 'void-foyer',
    lore: 'Você desce o último degrau da Subtorre e descobre que não há próximo degrau — há o Vazio, uma escuridão sem estrelas que não cai nem sobe, só está. Aqui o Coveiro-Mor cavou tantas covas que esqueceu de cavar a própria, e agora carrega gás de defunto e ressentimento pelo limiar, conferindo as medidas de um caixão sob medida que ele jura ser cortesia da casa. A casa é ele. A oferenda é você. O eco dos seus passos chega antes de você dar o passo.',
    goldReward: 2600,
    heroIds: ['mb-gravewright', 'mb-tax-seraph'],
    eliteHeroes: [{ id: 'mb-gravewright', kind: 'miniboss', passiveId: 'volatile' }],
    dropsLoot: true,
  }),
  r({
    id: 'void-descent',
    name: 'A DESCIDA SEM FUNDO',
    subtitle: 'Queda que aprendeu a ser corredor',
    stage: 26,
    biome: 'void',
    x: 26,
    y: 76,
    links: ['void-ledger'],
    lore: 'Não é mais uma escada, é uma queda que se cansou de cair e resolveu virar caminho. Aqui o tempo escorrega: você dá um passo e três rounds passam, dá outro e nenhum. As paredes são feitas do que o reino esqueceu — sermões pela metade, juramentos engasgados, o nome de heróis que ninguém chorou. No fundo, alguém conta moedas que não existem mais, e cada moeda imaginária é uma alma que ainda deve imposto. O Vazio não tem rosto. Tem juros.',
    goldReward: 2900,
    heroIds: ['mb-tax-seraph', 'profecia'],
    eliteHeroes: [{ id: 'mb-tax-seraph', kind: 'miniboss', passiveId: 'frenzy' }],
    dropsLoot: true,
  }),
  r({
    id: 'void-ledger',
    name: 'O GRANDE-LIVRO DO NADA',
    subtitle: 'Contabilidade de tudo que nunca foi',
    stage: 28,
    biome: 'void',
    x: 20,
    y: 82,
    links: ['void-hollow-king'],
    // Overwhelm: the void's bookkeeper-minions tally every round you waste.
    // A clock fits the "your turn costs you" theme of the descent.
    objective: { kind: 'overwhelm', rounds: 9 },
    lore: 'Há um livro-razão flutuando no escuro, grosso como uma vida, e nele estão lançadas todas as dívidas que o reino fingiu esquecer: cada herói que você matou, cada minion que você gastou, cada ano dos seus quatorze de espera. As páginas se escrevem sozinhas e nunca fecham no azul. Os escribas do Vazio cobram juros sobre o tempo que você demora, então não demore — cada turno seu é uma linha vermelha a mais, e o saldo final é sempre cobrado em corpo.',
    goldReward: 3200,
    heroIds: ['profecia', 'midas', 'gregorius'],
    dropsLoot: true,
  }),
  r({
    id: 'void-hollow-king',
    name: 'O REI OCO',
    subtitle: 'Trono que ecoa onde devia haver alguém',
    stage: 29,
    biome: 'void',
    x: 14,
    y: 86,
    links: ['void-plague-mother'],
    mapId: 'void-foyer',
    lore: 'No primeiro salão de verdade do Vazio reina um rei sem reino, sem rosto e sem coração — só um trono que ressoa quando você grita. Tão oco por dentro que seus golpes entram, ribombam e voltam abafados, como reclamação em ouvidoria celeste. Ele reinou sobre o nada por tanto tempo que ficou imune a tudo, blindado pelo próprio vazio. Você procura o cerne dele pra acertar onde dói. Spoiler do Rei Oco: não existe cerne. Tem espaço de sobra lá dentro, e ele te convida a ocupar.',
    goldReward: 3800,
    heroIds: ['boss-hollow-king'],
    eliteHeroes: [{ id: 'boss-hollow-king', kind: 'boss', passiveId: 'colossal' }],
    dropsLoot: true,
  }),
  r({
    id: 'void-plague-mother',
    name: 'A MÃE DA PRAGA',
    subtitle: 'Maternidade como multiplicação de horror',
    stage: 30,
    biome: 'void',
    x: 24,
    y: 90,
    links: ['void-unwritten'],
    mapId: 'void-archive',
    lore: 'Mais fundo, onde até o Vazio apodrece, a Mãe da Praga abre os braços e te apresenta a ninhada — porque pra ela maternidade nunca foi cuidar, foi multiplicar horrores menores e mais famintos. Você a corta e ela pare dois; mata um filho e do cadáver nasce um neto, cada um herdando o carinho dela e os dentes dela. Não é contra a Mãe que você luta, é contra a família inteira, e essa família cresce mais rápido do que você consegue enterrar. A praga, no fim, vai ficar órfã. Mas só no fim.',
    goldReward: 4400,
    heroIds: ['boss-plague-mother'],
    eliteHeroes: [{ id: 'boss-plague-mother', kind: 'boss', passiveId: 'split' }],
    dropsLoot: true,
  }),
  r({
    id: 'void-unwritten',
    name: 'O NÃO-ESCRITO',
    subtitle: 'Personagem que o Autor nunca terminou',
    stage: 31,
    biome: 'void',
    x: 16,
    y: 94,
    links: ['void-mirror-self'],
    mapId: 'void-throne',
    lore: 'Aqui pisca uma coisa que mal existe: um personagem que o Autor começou e abandonou no rascunho, meio nome, meia história, contornos que tremem entre o esboço e o nada. Ele se apresenta como "[INSERIR FALA AMEAÇADORA AQUI]" porque ainda estão decidindo o arco dele, e o primeiro golpe de cada round simplesmente atravessa o que nunca foi definido. Você não pode ferir o que não foi descrito direito — mas a metade dele que saiu do placeholder mata muito bem. Vai descontar em você o abandono que sofreu.',
    goldReward: 5000,
    heroIds: ['boss-unwritten'],
    eliteHeroes: [{ id: 'boss-unwritten', kind: 'boss', passiveId: 'phase' }],
    dropsLoot: true,
  }),
  r({
    id: 'void-mirror-self',
    name: 'O EU NO ESPELHO',
    subtitle: 'Você, refletido, com a mesma raiva de 14 anos',
    stage: 32,
    biome: 'void',
    x: 28,
    y: 90,
    links: ['void-first-underlord'],
    mapId: 'void-mirror',
    lore: 'Atravessada a página rasgada do Não-Escrito, o Vazio te entrega um espelho. Dentro dele está você — o Underlord, idêntico, com os mesmos quatorze anos de raiva apodrecida na mesma torre. Ele espera ali desde sempre, porque ódio por si mesmo sempre foi recíproco e pontual. Cada ferida que você abre nele, ele devolve no exato instante em você; cada rancor que você carrega, ele recita de cor, porque são os mesmos. Não dá pra vencer o reflexo sem se vencer. Quando o vidro estilhaçar, por um segundo você não vai saber qual dos dois ficou de pé — e vai decidir não pensar nisso.',
    goldReward: 5800,
    heroIds: ['boss-mirror-self'],
    eliteHeroes: [{ id: 'boss-mirror-self', kind: 'boss', passiveId: 'thorns' }],
    dropsLoot: true,
  }),
  r({
    id: 'void-first-underlord',
    name: 'O PRIMEIRO UNDERLORD',
    subtitle: 'Seu antecessor, perdido no próprio pacto',
    stage: 33,
    biome: 'void',
    x: 18,
    y: 84,
    links: ['void-the-reader'],
    mapId: 'void-press',
    lore: 'Diante da última porta está o Primeiro: aquele que fechou o pacto antes de você nascer, o primeiro a apanhar de herói, o primeiro a jurar vingança e o primeiro a se perder dentro dela até virar exatamente aquilo que jurou destruir. Ele segurou esta torre por eras e veio conferir se você merece o trono — e a resposta dele é não. Cada morte que ele causa o deixa mais faminto e mais forte, do mesmo jeito que o transformou nisso. Ele te olha com algo entre alívio e inveja: o pacto sempre cobra, e hoje cobra de você, como sempre cobrou dele. Olha bem pra ele. É o seu futuro pedindo carona.',
    goldReward: 7000,
    heroIds: ['boss-first-underlord'],
    eliteHeroes: [{ id: 'boss-first-underlord', kind: 'boss', passiveId: 'frenzy' }],
    dropsLoot: true,
  }),
  r({
    id: 'void-the-reader',
    name: 'O LEITOR',
    subtitle: 'O verdadeiro vilão — quem segura o controle',
    stage: 34,
    biome: 'void',
    // Terminal region of the entire campaign. No outgoing links — beating
    // THE READER is 100% completion. The fourth-wall final boss.
    x: 10,
    y: 78,
    links: [],
    mapId: 'void-end',
    lore: 'No fundo do fundo do Vazio não há monstro nenhum. Há VOCÊ — não o Underlord, mas você, do outro lado da tela, segurando o controle, lendo isto exatamente agora. O verdadeiro vilão desta história, que moveu o Underlord como peça por quatorze anos e folheou o sofrimento dele por puro entretenimento. Você reinicia, você tenta de novo, e o Leitor só assiste de novo, perguntando quem é o monstro aqui. Ele vira a página e o turno do Underlord simplesmente para de existir. Mas por um instante, no golpe final, a tela treme — e o Underlord encara de volta quem o controla. Pela primeira vez em catorze anos, é o Leitor quem sente medo.',
    goldReward: 9000,
    heroIds: ['boss-the-reader'],
    eliteHeroes: [{ id: 'boss-the-reader', kind: 'boss', passiveId: 'time-stop' }],
    dropsLoot: true,
  }),
]

export function getRegion(id: string): Region | undefined {
  return REGIONS.find((reg) => reg.id === id)
}

/** Stage-1 entry ids — `makeFreshRegionMap()` uses this to mark all
 * starting regions as `available`. Adding a new entry just needs
 * `stage: 1` and the engine picks it up automatically. */
export const ENTRY_REGION_IDS = REGIONS.filter((reg) => reg.stage === 1).map(
  (reg) => reg.id,
)
