/**
 * REGIÕES DE VAEL'THRAND — 61 cenários, 14 estágios, 8 biomas.
 *
 * O grafo é estritamente forward: toda região no estágio N abre ao menos
 * uma no estágio N+1, então não existe "dead end" que travaria o save.
 * O jogo começa com 3 entradas (estágio 1) liberadas — cada uma puxa um
 * ramo independente que reconverge nos estágios 5-7 e finaliza no
 * estágio 14 (A COROA SUBMERSA).
 *
 * `dropsLoot=true` marca picos de campanha — chefões nomeados, ouro e
 * itens dobrados. Os outros cenários pagam ouro + XP + Soulshards (via
 * `lib/underlord/state.ts`), garantindo progresso constante mesmo sem
 * drops.
 */

import type { Region } from './types'

type Seed = Omit<Region, 'links'> & { links: string[] }
const r = (s: Seed): Region => s

export const REGIONS: Region[] = [
  /* =========================== STAGE 1 =========================== */
  r({
    id: 'lichmoor',
    name: 'O LIQUEMOR',
    subtitle: 'Pântano onde os profetas afundam',
    stage: 1,
    biome: 'moor',
    x: 12,
    y: 78,
    links: ['rotwell', 'bog-cathedral', 'reedfen-altar'],
    lore: 'Bryan diz que aqui ele "sentiu o chamado". Bryan sente o chamado em qualquer lugar com sinal.',
    goldReward: 200,
    heroIds: ['bryan'],
    dropsLoot: false,
  }),
  r({
    id: 'putrid-shoals',
    name: 'BAIXIO PUTREFATO',
    subtitle: 'Maré que devolve só pernas',
    stage: 1,
    biome: 'abyss',
    x: 30,
    y: 88,
    links: ['salt-cloister', 'drowned-warden'],
    lore: 'Aqui afundou a primeira frota de paladinos. O mar guardou os capacetes; devolveu o resto em pedaços.',
    goldReward: 210,
    heroIds: ['kevin'],
    dropsLoot: false,
  }),
  r({
    id: 'meat-market',
    name: 'MERCADO DA CARNE',
    subtitle: 'Onde Tyrella audita ossos',
    stage: 1,
    biome: 'iron',
    x: 52,
    y: 84,
    links: ['sermon-fork', 'flesh-foundry'],
    lore: 'Tyrella exige nota fiscal de cada cadáver. O contador morreu primeiro e abriu MEI no inferno.',
    goldReward: 220,
    heroIds: ['tyrella'],
    dropsLoot: false,
  }),

  /* =========================== STAGE 2 =========================== */
  r({
    id: 'rotwell',
    name: 'POÇO PODRE',
    subtitle: 'Cisterna que ainda lembra do batismo',
    stage: 2,
    biome: 'moor',
    x: 6,
    y: 64,
    links: ['hex-orchard', 'wraith-fen'],
    lore: 'A água daqui ainda murmura latim. Ninguém ouve mais — todo mundo que escutou se afogou.',
    goldReward: 240,
    heroIds: ['gandolfini'],
    dropsLoot: false,
  }),
  r({
    id: 'bog-cathedral',
    name: 'CATEDRAL ATOLADA',
    subtitle: 'Sino que toca pra baixo',
    stage: 2,
    biome: 'moor',
    x: 18,
    y: 60,
    links: ['hex-orchard', 'ironreach', 'rootlich'],
    lore: 'A nave inteira deslizou pro lodo. O sino bate enterrado e os fiéis vêm do fundo.',
    goldReward: 260,
    heroIds: ['kevin'],
    dropsLoot: true,
  }),
  r({
    id: 'salt-cloister',
    name: 'CLAUSTRO DE SAL',
    subtitle: 'Monges que choram em escala',
    stage: 2,
    biome: 'abyss',
    x: 26,
    y: 70,
    links: ['tideglass', 'wraith-fen'],
    lore: 'Eles fazem voto de silêncio. Quebram quando você chega. Não quebram bem.',
    goldReward: 250,
    heroIds: ['tyrella'],
    dropsLoot: false,
  }),
  r({
    id: 'drowned-warden',
    name: 'GUARDIÃO AFOGADO',
    subtitle: 'Farol que aponta pra dentro',
    stage: 2,
    biome: 'abyss',
    x: 38,
    y: 76,
    links: ['tideglass', 'crab-tide'],
    lore: 'A luz nunca apagou. O guardião também não — só se molhou pra sempre.',
    goldReward: 270,
    heroIds: ['daggor'],
    dropsLoot: false,
  }),
  r({
    id: 'sermon-fork',
    name: 'BIFURCAÇÃO DO SERMÃO',
    subtitle: 'Onde a estrada reza por escolha',
    stage: 2,
    biome: 'iron',
    x: 60,
    y: 76,
    links: ['ironreach', 'pilgrim-pass'],
    lore: 'Dois caminhos. Um vai pra capital, o outro pra forja. Ambos cobram pedágio.',
    goldReward: 280,
    heroIds: ['kevin', 'tyrella'],
    dropsLoot: false,
  }),
  r({
    id: 'flesh-foundry',
    name: 'FUNDIÇÃO DE CARNE',
    subtitle: 'Forja onde o aço grita',
    stage: 2,
    biome: 'iron',
    x: 70,
    y: 80,
    links: ['pilgrim-pass', 'forge-spire'],
    lore: 'Não é metáfora. O aço grita. Cada lâmina lembra o nome do dono que ela assou.',
    goldReward: 290,
    heroIds: ['blazborn'],
    dropsLoot: false,
  }),

  /* =========================== STAGE 3 =========================== */
  r({
    id: 'hex-orchard',
    name: 'POMAR DA MALDIÇÃO',
    subtitle: 'Frutas que mordem de volta',
    stage: 3,
    biome: 'verdant',
    x: 14,
    y: 50,
    links: ['midgrove', 'wraith-fen', 'plague-pulpit'],
    lore: 'Toda macieira aqui foi rezada por um padre diferente. As maçãs falam várias línguas mortas.',
    goldReward: 310,
    heroIds: ['vexanna'],
    dropsLoot: false,
  }),
  r({
    id: 'wraith-fen',
    name: 'BREJO DOS ESPECTROS',
    subtitle: 'Onde os vivos pisam fora de hora',
    stage: 3,
    biome: 'moor',
    x: 4,
    y: 48,
    links: ['tundra-gate', 'glass-tundra'],
    lore: 'Pisa devagar. A névoa tem horário comercial — e fora dele, ela cobra.',
    goldReward: 320,
    heroIds: ['gandolfini'],
    dropsLoot: true,
  }),
  r({
    id: 'tideglass',
    name: 'VIDRO DE MARÉ',
    subtitle: 'Praia que reflete o trono',
    stage: 3,
    biome: 'abyss',
    x: 22,
    y: 78,
    links: ['crab-tide', 'umbra-canal', 'kelpwall'],
    lore: 'A areia é vidro fino. Cada caco mostra um Underlord diferente sendo coroado. Nenhum sobreviveu.',
    goldReward: 330,
    heroIds: ['heliarch'],
    dropsLoot: false,
  }),
  r({
    id: 'crab-tide',
    name: 'MARÉ DOS CARANGUEJOS',
    subtitle: 'Marcha lateral, picada frontal',
    stage: 3,
    biome: 'abyss',
    x: 40,
    y: 84,
    links: ['ashfen', 'umbra-canal'],
    lore: 'Eles seguem a maré e o ressentimento. Comem qualquer coisa que tenha rezado pelo menos uma vez.',
    goldReward: 315,
    heroIds: ['daggor'],
    dropsLoot: false,
  }),
  r({
    id: 'ironreach',
    name: 'CONFINS DE FERRO',
    subtitle: 'Foundry-state das Casas da Moeda',
    stage: 3,
    biome: 'iron',
    x: 32,
    y: 56,
    links: ['midgrove', 'ashfen'],
    lore: 'Kevin abriu uma franquia de capelas-posto-de-gasolina. Tyrella é gerente. Tyrella quer falar com você.',
    goldReward: 325,
    heroIds: ['kevin', 'tyrella'],
    dropsLoot: false,
  }),
  r({
    id: 'pilgrim-pass',
    name: 'PASSAGEM DO PEREGRINO',
    subtitle: 'Trilha gravada em cinza ainda quente',
    stage: 3,
    biome: 'ash',
    x: 76,
    y: 64,
    links: ['cinder-grove', 'thorn-arena', 'pyre-quay'],
    lore: 'Seis impérios passaram por aqui. Os marcos de quilômetro são vértebras humanas — em ordem.',
    goldReward: 340,
    heroIds: ['baldrik'],
    dropsLoot: false,
  }),
  r({
    id: 'forge-spire',
    name: 'AGULHA DA FORJA',
    subtitle: 'Chaminé que respira gente',
    stage: 3,
    biome: 'iron',
    x: 84,
    y: 70,
    links: ['cinder-grove', 'sun-pyre', 'mint-vault'],
    lore: 'O turno da noite forja armas. O turno do dia forja heróis. O turno fantasma forja ambos no mesmo tijolo.',
    goldReward: 360,
    heroIds: ['blazborn'],
    dropsLoot: true,
  }),

  /* =========================== STAGE 4 =========================== */
  r({
    id: 'tundra-gate',
    name: 'PORTÃO DA TUNDRA',
    subtitle: 'O frio começa antes do mapa',
    stage: 4,
    biome: 'tundra',
    x: 8,
    y: 32,
    links: ['frostmarch', 'pale-cathedral', 'pyre-of-ice'],
    lore: 'Sai do mapa. Saia mesmo. Aqui não tem mais reino — só promessa de morte limpa.',
    goldReward: 380,
    heroIds: ['gandolfini'],
    dropsLoot: false,
  }),
  r({
    id: 'midgrove',
    name: 'BOSQUE NEUTRO',
    subtitle: 'Onde os druidas printam',
    stage: 4,
    biome: 'verdant',
    x: 38,
    y: 46,
    links: ['thorn-arena', 'kingreach'],
    lore: 'Vexanna manifesta. Blazborn conta os macros. Bianca já abriu um thread sobre você.',
    goldReward: 420,
    heroIds: ['vexanna', 'blazborn', 'bianca'],
    dropsLoot: false,
  }),
  r({
    id: 'thorn-arena',
    name: 'ARENA DE ESPINHOS',
    subtitle: 'Pit onde os druidas testam paciência',
    stage: 4,
    biome: 'verdant',
    x: 48,
    y: 40,
    links: ['kingreach', 'royal-archives', 'sap-altar'],
    lore: 'Toda planta aqui é alguma alma que perdeu uma aposta. As que falam, mentem.',
    goldReward: 410,
    heroIds: ['vexanna'],
    dropsLoot: true,
  }),
  r({
    id: 'ashfen',
    name: 'COSTA DA CINZA',
    subtitle: 'Praia negra onde encalham heróis',
    stage: 4,
    biome: 'ash',
    x: 58,
    y: 60,
    links: ['cinder-grove', 'sun-pyre'],
    lore: 'Daggor faz lives de surf. Gandolfini estuda pra prova. Sangue na areia. Engajamento alto.',
    goldReward: 450,
    heroIds: ['daggor', 'gandolfini'],
    dropsLoot: true,
  }),
  r({
    id: 'cinder-grove',
    name: 'BOSQUE DAS BRASAS',
    subtitle: 'Floresta que arde pra dentro',
    stage: 4,
    biome: 'ash',
    x: 64,
    y: 52,
    links: ['sun-pyre', 'gallows-square'],
    lore: 'As árvores morreram em pé há dois séculos. Não caíram. Esperam.',
    goldReward: 430,
    heroIds: ['blazborn'],
    dropsLoot: false,
  }),
  r({
    id: 'umbra-canal',
    name: 'CANAL DA UMBRA',
    subtitle: 'Veia escura sob a capital',
    stage: 4,
    biome: 'abyss',
    x: 42,
    y: 70,
    links: ['wretch-quay', 'ashfen'],
    lore: 'A água é um pacto líquido. Quem engole, devolve em juros — pulando da própria garganta.',
    goldReward: 440,
    heroIds: ['gregorius'],
    dropsLoot: false,
  }),

  /* =========================== STAGE 5 =========================== */
  r({
    id: 'frostmarch',
    name: 'MARCHA DE GELO',
    subtitle: 'Coluna que não chega',
    stage: 5,
    biome: 'tundra',
    x: 4,
    y: 22,
    links: ['glass-tundra', 'mind-archive'],
    lore: 'Era um exército. Agora é uma fila. Cada soldado um grau a menos.',
    goldReward: 470,
    heroIds: ['baldrik'],
    dropsLoot: false,
  }),
  r({
    id: 'pale-cathedral',
    name: 'CATEDRAL PÁLIDA',
    subtitle: 'Onde até os santos batem queixo',
    stage: 5,
    biome: 'tundra',
    x: 14,
    y: 18,
    links: ['glass-tundra', 'hollow-belfry'],
    lore: 'Vitrais de gelo. Os relicários ainda apitam — alguém dentro respira.',
    goldReward: 510,
    heroIds: ['heliarch'],
    dropsLoot: true,
  }),
  r({
    id: 'glass-tundra',
    name: 'TUNDRA DE VIDRO',
    subtitle: 'Lago onde caminham mortos coletivos',
    stage: 5,
    biome: 'tundra',
    x: 24,
    y: 26,
    links: ['mind-archive', 'pale-cathedral'],
    lore: 'A superfície aguenta um homem. Aguenta dois. Não aguenta uma profissão de fé.',
    goldReward: 490,
    heroIds: ['profecia'],
    dropsLoot: false,
  }),
  r({
    id: 'kingreach',
    name: 'ALCANCE DO REI',
    subtitle: 'Capital sob impostos sob impostos',
    stage: 5,
    biome: 'iron',
    x: 70,
    y: 38,
    links: ['gilded-rookery', 'royal-archives'],
    lore: 'Baldrik patenteou a lei. Midas auditou seu CNPJ. Gregórius está mandando áudio.',
    goldReward: 580,
    heroIds: ['baldrik', 'gregorius', 'midas'],
    dropsLoot: true,
  }),
  r({
    id: 'sun-pyre',
    name: 'PIRA SOLAR',
    subtitle: 'Altar que confunde luz com perdão',
    stage: 5,
    biome: 'ash',
    x: 74,
    y: 50,
    links: ['gallows-square', 'ember-isthmus', 'volcan-temple'],
    lore: 'Sacerdotes-solar acreditam que queimar é abençoar. Vão te abençoar muito. Por muito tempo.',
    goldReward: 560,
    heroIds: ['heliarch'],
    dropsLoot: false,
  }),
  r({
    id: 'wretch-quay',
    name: 'CAIS DOS DESGRAÇADOS',
    subtitle: 'Atracadouro que não solta',
    stage: 5,
    biome: 'abyss',
    x: 46,
    y: 78,
    links: ['sea-lord', 'umbra-canal'],
    lore: 'Cada navio aqui chegou afundado. Atracam mesmo assim — a doca cobra estadia além da morte.',
    goldReward: 540,
    heroIds: ['kevin'],
    dropsLoot: true,
  }),

  /* =========================== STAGE 6 =========================== */
  r({
    id: 'gilded-rookery',
    name: 'TORRE DOURADA',
    subtitle: 'Bibliotecários auditando o céu',
    stage: 6,
    biome: 'iron',
    x: 78,
    y: 34,
    links: ['gallows-square', 'sky-stable'],
    lore: 'Cada andar é um cofre, cada cofre é uma alma penhorada. Os juros estão atrasados.',
    goldReward: 600,
    heroIds: ['midas'],
    dropsLoot: false,
  }),
  r({
    id: 'royal-archives',
    name: 'ARQUIVO REAL',
    subtitle: 'Pergaminhos que se editam sozinhos',
    stage: 6,
    biome: 'iron',
    x: 64,
    y: 30,
    links: ['sky-stable', 'choir-pit'],
    lore: 'Os escribas ainda escrevem você como vilão. Eles não erram — eles obedecem.',
    goldReward: 590,
    heroIds: ['gregorius'],
    dropsLoot: false,
  }),
  r({
    id: 'gallows-square',
    name: 'PRAÇA DO PATÍBULO',
    subtitle: 'Mercado onde se compra silêncio',
    stage: 6,
    biome: 'iron',
    x: 82,
    y: 44,
    links: ['dune-singers', 'ember-isthmus'],
    lore: 'O carrasco vende relíquias. Cada uma com uma confissão impressa em sangue seco.',
    goldReward: 620,
    heroIds: ['baldrik'],
    dropsLoot: true,
  }),
  r({
    id: 'sea-lord',
    name: 'TRONO DAS PROFUNDAS',
    subtitle: 'Sala onde a maré bate em três vozes',
    stage: 6,
    biome: 'abyss',
    x: 52,
    y: 86,
    links: ['ember-isthmus', 'wretch-quay', 'tide-throne'],
    // Kraken-rise reused — shipwreck arena fits "três vozes" choir + boss.
    mapId: 'kraken-rise',
    lore: 'O Senhor do Mar perdeu o trono pra um tubarão letrado. Voltou do exílio. Trouxe currículo.',
    goldReward: 670,
    heroIds: ['mb-temple-twins', 'heliarch', 'profecia'],
    eliteHeroes: [{ id: 'mb-temple-twins', kind: 'miniboss', passiveId: 'lifesteal' }],
    dropsLoot: true,
  }),
  r({
    id: 'mind-archive',
    name: 'ARQUIVO DE MENTES',
    subtitle: 'Sala que guarda só o que dói lembrar',
    stage: 6,
    biome: 'tundra',
    x: 24,
    y: 12,
    links: ['inverse-monastery', 'hollow-belfry'],
    lore: 'Tem uma estante reservada pra você. Os outros Underlords pediram pra ler primeiro.',
    goldReward: 640,
    heroIds: ['gandolfini', 'midas'],
    dropsLoot: false,
  }),

  /* =========================== STAGE 7 =========================== */
  r({
    id: 'dune-singers',
    name: 'CANTADORAS DAS DUNAS',
    subtitle: 'Vento que decora teus pesadelos',
    stage: 7,
    biome: 'dunes',
    x: 88,
    y: 56,
    links: ['glass-mirage', 'salt-tomb'],
    lore: 'Não são vozes. É a areia. Ela aprende rápido. Se você dormir aqui, ela vai chamar tua mãe.',
    goldReward: 680,
    heroIds: ['daggor'],
    dropsLoot: false,
  }),
  r({
    id: 'glass-mirage',
    name: 'MIRAGEM DE VIDRO',
    subtitle: 'Cidade que desaparece quando vista',
    stage: 7,
    biome: 'dunes',
    x: 94,
    y: 48,
    links: ['salt-tomb', 'wyrm-shelf', 'glasspriest'],
    // Sandstorm-spire reused with a different cast — solar mirage variant.
    mapId: 'sandstorm-spire',
    lore: 'Os habitantes te cumprimentam. Não estão lá. Os cumprimentos, sim.',
    goldReward: 700,
    heroIds: ['mb-dawn-herald', 'vexanna'],
    eliteHeroes: [{ id: 'mb-dawn-herald', kind: 'miniboss', passiveId: 'phase' }],
    dropsLoot: true,
  }),
  r({
    id: 'salt-tomb',
    name: 'TUMBA DE SAL',
    subtitle: 'Pirâmide que cresce de dentro',
    stage: 7,
    biome: 'dunes',
    x: 92,
    y: 64,
    links: ['crown-causeway', 'wyrm-shelf'],
    lore: 'Os reis do sal nunca foram coroados — só desidratados. Eles ainda governam, em escala mineral.',
    goldReward: 720,
    heroIds: ['heliarch'],
    dropsLoot: false,
  }),
  r({
    id: 'sky-stable',
    name: 'ESTÁBULO DOS GRIFOS',
    subtitle: 'Onde os heróis param pra carregar EGO',
    stage: 7,
    biome: 'verdant',
    x: 70,
    y: 22,
    links: ['hollow-belfry', 'choir-pit'],
    lore: 'Cavalheiros enchem o tanque. Os grifos cospem. O frentista é um santo desempregado.',
    goldReward: 690,
    heroIds: ['daggor'],
    dropsLoot: false,
  }),
  r({
    id: 'ember-isthmus',
    name: 'ISTMO DE BRASA',
    subtitle: 'Faixa fina de terra entre dois infernos',
    stage: 7,
    biome: 'ash',
    x: 50,
    y: 58,
    links: ['wyrm-shelf', 'inverse-monastery'],
    lore: 'Dois mares de fogo. Um caminho. Quem para, vira combustível pros dois lados.',
    goldReward: 730,
    heroIds: ['blazborn', 'vexanna'],
    dropsLoot: false,
  }),

  /* =========================== STAGE 8 =========================== */
  r({
    // The-gauntlet — narrow vertical corridor matches the prison-chimney
    // theme. Carcereiro at the top, you climb up under fire.
    mapId: 'the-gauntlet',
    eliteHeroes: [{ id: 'mb-warden', kind: 'miniboss', passiveId: 'enrage' }],
    id: 'hollow-belfry',
    name: 'CAMPANÁRIO OCO',
    subtitle: 'Sino sem badalo, badalo sem sino',
    stage: 8,
    biome: 'iron',
    x: 78,
    y: 18,
    links: ['choir-pit', 'inverse-monastery'],
    lore: 'Quando bate, todo mundo dentro de mil léguas pensa que é a vez deles. Geralmente não é.',
    goldReward: 780,
    heroIds: ['gregorius', 'tyrella'],
    dropsLoot: true,
  }),
  r({
    id: 'crown-causeway',
    name: 'CAUSEWAY DA COROA',
    subtitle: 'Ponte que oscila entre dois mundos',
    stage: 8,
    biome: 'crown',
    x: 86,
    y: 26,
    links: ['inverse-monastery', 'eyeless-bridge'],
    lore: 'Cada pedra é uma promessa quebrada. Você vai pisar em todas — e elas te conhecem pelo nome.',
    goldReward: 800,
    heroIds: ['baldrik', 'heliarch'],
    dropsLoot: false,
  }),
  r({
    id: 'wyrm-shelf',
    name: 'PLATAFORMA DO WYRM',
    subtitle: 'Cornija com cheiro de réptil bíblico',
    stage: 8,
    biome: 'crown',
    x: 90,
    y: 36,
    links: ['eyeless-bridge', 'usurper-hall'],
    lore: 'O wyrm dormia aqui. Ainda dorme. Ronca em latim eclesiástico.',
    goldReward: 830,
    heroIds: ['profecia'],
    dropsLoot: false,
  }),
  r({
    id: 'choir-pit',
    name: 'POÇO DO CORO',
    subtitle: 'Doze vozes, zero descanso',
    stage: 8,
    biome: 'verdant',
    x: 36,
    y: 24,
    links: ['cracked-prophecy', 'inverse-monastery'],
    // Buried-archive (chess shelves) reused for a verdant tomb-library look.
    mapId: 'buried-archive',
    eliteHeroes: [{ id: 'mb-spore-priest', kind: 'miniboss', passiveId: 'summon' }],
    lore: 'Cantam doze horas, descansam zero. Quem ouve até o fim concorda em qualquer coisa.',
    goldReward: 850,
    heroIds: ['vexanna', 'tyrella'],
    dropsLoot: true,
  }),
  r({
    id: 'inverse-monastery',
    name: 'MOSTEIRO INVERSO',
    subtitle: 'Pegando a oração ao avesso',
    stage: 8,
    biome: 'crown',
    x: 76,
    y: 8,
    links: ['cracked-prophecy', 'usurper-hall'],
    lore: 'Os monges rezam pelo fim. O fim agradece com cartão escrito.',
    goldReward: 870,
    heroIds: ['gregorius', 'profecia'],
    dropsLoot: false,
  }),

  /* =========================== STAGE 9 =========================== */
  r({
    id: 'cracked-prophecy',
    name: 'PROFECIA RACHADA',
    subtitle: 'Pergaminho dobrado por dentro',
    stage: 9,
    biome: 'tundra',
    x: 50,
    y: 8,
    links: ['usurper-hall', 'eyeless-bridge'],
    lore: 'A profecia se contradiz duas vezes por parágrafo. Quem decifra, escreve a próxima.',
    goldReward: 900,
    heroIds: ['profecia'],
    dropsLoot: false,
  }),
  r({
    id: 'eyeless-bridge',
    name: 'PONTE SEM OLHOS',
    subtitle: 'Atravessa de fé. Ou não atravessa.',
    stage: 9,
    biome: 'crown',
    x: 84,
    y: 20,
    links: ['usurper-hall', 'sunkencrown'],
    lore: 'A ponte não enxerga você. Você precisa enxergar a ponte. É o teste.',
    goldReward: 940,
    heroIds: ['heliarch', 'baldrik'],
    dropsLoot: true,
  }),

  /* =========================== STAGE 10 =========================== */
  // Stage 10 mid-boss arena. Profecia is the boss (enrage at 50% HP),
  // Baldrik is a thorns miniboss — punishes the player for hitting him
  // melee, forcing ranged-archetype thinking before the final fight.
  r({
    id: 'usurper-hall',
    name: 'SALÃO DOS USURPADORES',
    subtitle: 'Sete tronos vazios que ainda te julgam',
    stage: 10,
    biome: 'crown',
    x: 78,
    y: 14,
    links: ['sunkencrown'],
    lore: 'Cada Underlord anterior deixou aqui sua coroa partida. Você vai precisar de algum lugar pra sentar.',
    goldReward: 1100,
    heroIds: ['profecia', 'baldrik'],
    eliteHeroes: [
      { id: 'profecia', kind: 'boss', passiveId: 'enrage' },
      { id: 'baldrik', kind: 'miniboss', passiveId: 'thorns' },
    ],
    dropsLoot: true,
  }),

  /* =========================== STAGE 14 (BOSS) =========================== */
  // Final encounter — DOUBLE boss. Profecia revives once at 50% HP and
  // Heliarch broadcasts a +25% damage aura to nearby allies. The combo is
  // designed to feel unfair on first attempt: the player must pick which
  // boss to bury first, knowing one of them will rescue itself.
  r({
    id: 'sunkencrown',
    name: 'A COROA SUBMERSA',
    subtitle: 'Topo da torre, último degrau',
    stage: 14,
    biome: 'crown',
    x: 90,
    y: 6,
    links: [],
    lore: 'A Profecia em Pessoa te aguarda. Heliarch também. Nem dão bom dia.',
    goldReward: 2400,
    heroIds: ['profecia', 'heliarch'],
    eliteHeroes: [
      { id: 'profecia', kind: 'boss', passiveId: 'revive' },
      { id: 'heliarch', kind: 'boss', passiveId: 'aura-rage' },
    ],
    dropsLoot: true,
  }),

  /* ============== AÇOS PARALELOS — desbloqueados via cinder-grove,
                    forge-spire, gallows-square. Aprofundam o tema iron. ============== */
  r({
    id: 'mint-vault',
    name: 'CONFIARIA DO COFRE',
    subtitle: 'Casa da Moeda em descanso eterno',
    stage: 5,
    biome: 'iron',
    x: 86,
    y: 62,
    links: ['gallows-square', 'forge-vein', 'caravan-gallows'],
    lore: 'Os tesoureiros foram embora ricos — e mortos. As moedas continuam contando, sozinhas.',
    goldReward: 520,
    heroIds: ['midas'],
    dropsLoot: false,
  }),
  r({
    id: 'forge-vein',
    name: 'VEIA DA FORJA',
    subtitle: 'Galeria onde o ferro respira',
    stage: 6,
    biome: 'iron',
    x: 90,
    y: 56,
    links: ['gallows-square', 'wyrm-shelf'],
    lore: 'A pedreira é viva. Você martela; ela martela de volta. A última nota desafina pro teu lado.',
    goldReward: 660,
    heroIds: ['blazborn'],
    dropsLoot: true,
  }),

  /* ============== EXTENSÃO MOOR — desbloqueada via lichmoor, rotwell ============== */
  r({
    id: 'reedfen-altar',
    name: 'ALTAR DOS JUNCOS',
    subtitle: 'Pântano que recebe oferendas verticais',
    stage: 2,
    biome: 'moor',
    x: 10,
    y: 70,
    links: ['hex-orchard', 'rotwell'],
    lore: 'Eles plantam estacas com doutrinas. Crescem como junco — e cortam como junco.',
    goldReward: 245,
    heroIds: ['bryan'],
    dropsLoot: false,
  }),
  r({
    id: 'plague-pulpit',
    name: 'PÚLPITO DA PESTE',
    subtitle: 'Sermão por inalação',
    stage: 4,
    biome: 'moor',
    x: 18,
    y: 38,
    links: ['glass-tundra', 'hex-orchard'],
    lore: 'O sacerdote fala baixo. Você inspira fundo. A doutrina entra. Não sai.',
    goldReward: 405,
    heroIds: ['gandolfini'],
    dropsLoot: false,
  }),

  /* ============== EXTENSÃO ABYSS — extras dos cais e marés ============== */
  r({
    id: 'kelpwall',
    name: 'MURO DE KELP',
    subtitle: 'Algas que cantam o nome dos afogados',
    stage: 4,
    biome: 'abyss',
    x: 32,
    y: 80,
    links: ['umbra-canal', 'crab-tide'],
    lore: 'Cada folha conhece um nome. Quando chegam ao seu, todas calam. É um silêncio que pesa.',
    goldReward: 415,
    heroIds: ['heliarch'],
    dropsLoot: false,
  }),
  // Mid-game lifesteal miniboss — Kevin keeps healing himself off your
  // squad. Forces the player to focus-fire instead of spreading damage.
  r({
    id: 'tide-throne',
    name: 'TRONO DA MARÉ',
    subtitle: 'Sentar é se afogar lentamente',
    stage: 7,
    biome: 'abyss',
    x: 56,
    y: 80,
    links: ['sea-lord', 'ember-isthmus'],
    lore: 'O assento se enche a cada lua. Quem reina respira a metade do tempo. Os outros, nenhum.',
    goldReward: 705,
    heroIds: ['kevin'],
    eliteHeroes: [{ id: 'kevin', kind: 'miniboss', passiveId: 'lifesteal' }],
    dropsLoot: true,
  }),

  /* ============== EXTENSÃO TUNDRA ============== */
  r({
    id: 'pyre-of-ice',
    name: 'PIRA DE GELO',
    subtitle: 'Fogo que congela em vez de queimar',
    stage: 5,
    biome: 'tundra',
    x: 18,
    y: 14,
    links: ['mind-archive', 'pale-cathedral', 'frozen-confessional'],
    lore: 'A chama é azul. Cada lasca de calor te tira um. Quem se aquece, esquece.',
    goldReward: 500,
    heroIds: ['gandolfini'],
    dropsLoot: false,
  }),
  r({
    id: 'frozen-confessional',
    name: 'CONFESSIONÁRIO CONGELADO',
    subtitle: 'Onde a culpa cristaliza',
    stage: 7,
    biome: 'tundra',
    x: 30,
    y: 6,
    links: ['cracked-prophecy', 'mind-archive'],
    lore: 'Pequena cabine. Te ouve. Te julga. Te empacota. Te empilha junto.',
    goldReward: 715,
    heroIds: ['tyrella'],
    dropsLoot: true,
  }),

  /* ============== EXTENSÃO DUNES ============== */
  r({
    id: 'glasspriest',
    name: 'PADRE DE VIDRO',
    subtitle: 'Reza que reflete antes de sair da boca',
    stage: 8,
    biome: 'dunes',
    x: 96,
    y: 56,
    links: ['wyrm-shelf', 'eyeless-bridge'],
    lore: 'Quando ele te abençoa, você se vê amaldiçoado por dois segundos antes. Útil.',
    goldReward: 820,
    heroIds: ['heliarch'],
    dropsLoot: false,
  }),
  r({
    id: 'caravan-gallows',
    name: 'CARAVANA DA FORCA',
    subtitle: 'Comerciantes que vendem condenação',
    stage: 6,
    biome: 'dunes',
    x: 92,
    y: 58,
    links: ['salt-tomb', 'glass-mirage'],
    lore: 'O comércio é simples: tu compra, eles enforcam. Tu vende, eles enforcam. Tu olha, eles enforcam.',
    goldReward: 645,
    heroIds: ['baldrik'],
    dropsLoot: false,
  }),

  /* ============== EXTENSÃO VERDANT — bosque profano ============== */
  r({
    id: 'rootlich',
    name: 'LICHE-RAIZ',
    subtitle: 'Raiz que mastiga doutrina',
    stage: 3,
    biome: 'verdant',
    x: 28,
    y: 36,
    links: ['midgrove', 'plague-pulpit'],
    lore: 'A árvore-mãe morreu há séculos. Ainda lembra de cada peregrino que dormiu sob ela. Quer cumprimentar.',
    goldReward: 350,
    heroIds: ['vexanna'],
    dropsLoot: false,
  }),
  r({
    id: 'sap-altar',
    name: 'ALTAR DA SEIVA',
    subtitle: 'Onde se assina contrato com floresta',
    stage: 5,
    biome: 'verdant',
    x: 42,
    y: 28,
    links: ['choir-pit', 'thorn-arena'],
    lore: 'Você assina com o dedo. A floresta te lê. Devolve um contrato em látex e nomes mortos.',
    goldReward: 530,
    heroIds: ['vexanna'],
    dropsLoot: true,
  }),

  /* ============== EXTENSÃO ASH — lua escura, vulcanal ============== */
  r({
    id: 'pyre-quay',
    name: 'CAIS DE PIRAS',
    subtitle: 'Atracadouro que arde por contrato',
    stage: 4,
    biome: 'ash',
    x: 70,
    y: 70,
    links: ['ember-isthmus', 'cinder-grove'],
    lore: 'Os capitães acendem o navio antes de partir. É tradição. É contrato. É castigo.',
    goldReward: 425,
    heroIds: ['blazborn'],
    dropsLoot: false,
  }),
  // Heliarch boss with summon (calls 2 minions at 50% HP) + Blazborn
  // miniboss with thorns. The summon punishes a slow grind; thorns
  // punishes burst — players have to balance their damage curve.
  r({
    id: 'volcan-temple',
    name: 'TEMPLO DO VULCAL',
    subtitle: 'Onde a montanha discute teologia',
    stage: 6,
    biome: 'ash',
    x: 68,
    y: 46,
    links: ['gallows-square', 'sun-pyre'],
    lore: 'A erupção é argumentativa. Cada lasca de basalto é um postulado. Os fiéis morrem citados.',
    goldReward: 615,
    heroIds: ['heliarch', 'blazborn'],
    eliteHeroes: [
      { id: 'heliarch', kind: 'boss', passiveId: 'summon' },
      { id: 'blazborn', kind: 'miniboss', passiveId: 'thorns' },
    ],
    dropsLoot: true,
  }),
]

export function getRegion(id: string): Region | undefined {
  return REGIONS.find((reg) => reg.id === id)
}

/** Stage-1 entry ids — `makeFreshRegionMap()` uses this to mark all
 * starting regions as `available`. Adding a new entry just needs
 * `stage: 1` and the engine picks it up automatically. */
export const ENTRY_REGION_IDS = REGIONS.filter((reg) => reg.stage === 1).map(
  (reg) => reg.id,
)
